### ISSUE TITLE
Theme refactor frontend: header

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#10]
# Sample - http://localgov.dev.mark.ie

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity 

Notes:
- We are now printing branding block in header region (this region is never printed in localgov_theme)

**Comment by finnlewis** [comment]
@markconroy is this done for the sprint?

**Comment by markconroy** [comment]
Not fully. I need to look at menus when added to the secondary nav region.

**Comment by finnlewis** [comment]
At the working group meeting this week, we agreed that @cjstevens78 @msayoung and Dave would review the locaogov_base theme as part of this.
This is not quite ready for full review yet.

**Comment by markconroy** [comment]
I think this is ready for a review now.

I haven't done any work on mobile search or search regions, as I am not sure what is actually going to go into them.

**Comment by finnlewis** [comment]
Thanks @markconroy - I'm guessing it's not easy at this stage to do a pull request with these specific  changes in.  

@cjstevens78 @danchamp @msayoung any of you able to take a look ?

**Comment by markconroy** [comment]
We can create PRs to _change_ this to something else, but not a PR for this actual item. That's why I'm listing the files to look at when reviewing.

**Comment by andybroomfield** [comment]
@markconroy are all these changes included in the master branch?

**Comment by markconroy** [comment]
Yes, everything is in master currently.

**Comment by cjstevens78** [comment]
Looking good to me - couple of very minor things:

- Focus on the logo is inheriting the general focus style and looks odd (see screenshot)

<img width="464" alt="Screenshot 2021-06-14 at 14 35 22" src="https://user-images.githubusercontent.com/11304107/121901659-7fb1be00-cd1e-11eb-9384-45db5767a82c.png">

- I wonder if, when you have tabbed to ‘services’ and hit ‘enter’ to open the services menu, whether the next tab should focus to the first item in the services menu and not move onto the other menu options before landing on the services.

**Comment by markconroy** [comment]
hmmmm
1. I liked the look of the logo when focussed, but let's change it to an outline instead. Probably makes more sense.
2. I'm not sure what the best thing is for that focus state. I thought of that, but then if you don't want to go to a service, you have to tab all the way back up to the services button to close the services menu.

Anyone else have any thoughts on item 2?

**Comment by msayoung** [comment]
Do we know why we have this approach for the menus? (ie the toggle for the menu in the primary menu region and the actual menu in the secondary menu region)

As @cjstevens78 says I would expect the expanded item to come immediately after the toggle button in the tab / reading order - particularly for a screen reader user. 
If we don't move it closer to the toggle button (or even if we do) it might be good to add a close/hide button within that menu.

**Comment by msayoung** [comment]
also i have some weird hover styling on items over multiple lines. Just on Chrome. 
![Screenshot from 2021-06-14 17-34-43](https://user-images.githubusercontent.com/3852805/121927605-2904ae00-cd37-11eb-837f-38321ed738e2.png)

**Comment by cjstevens78** [comment]
@msayoung the toggled menu was inherited with the site when it came over from Brighton .. they just have the one link to 'services' and a click reveals it. We expanded on this to have more links at the top level but other than that it has just been left as is.

**Comment by finnlewis** [comment]
For the record, Lambeth designed a similar pattern for the main 'services' menu:

![image](https://user-images.githubusercontent.com/326588/121930878-2b6d0500-cd43-11eb-984e-a70edb45b606.png)

**Comment by danchamp** [comment]
Lambeth shows the pattern I'd expect - the visibility of the sub-menu can be controlled using the activating element (Council services) as a toggle, or by pressing escape when one of the child items has focus, in which case focus returns to the activating link.

What I don't like about Lambeth's implementation is that the activating element is an anchor with an href (/council-services), which is impossible to access with the keyboard or the mouse. It should be a button and a link to the services page appear in the menu, or there should be an adjacent button element for controlling the menu visibility.

**Comment by markconroy** [comment]
We could move the services button to the end of the header region, then when you click on it the next tabbable item will be the secondary menu. I left it at the beginning of that section because that's how it is in Croydon's website.

**Comment by msayoung** [comment]
I think that makes sense @markconroy - as far as you know is that the only menu that behaves like this?

**Comment by andybroomfield** [comment]
<img width="1219" alt="Screenshot 2021-06-16 at 4 08 46 pm" src="https://user-images.githubusercontent.com/1467480/122244882-27fd8900-cebd-11eb-91a5-547927219617.png">
As implemented on BHCC.
This is two menu blocks, a services menu and a business menu.
(Although we do have plans to change our menu stucture in the future).
These render using the secondary menu region.
These menus get duplicated in the mobile menu region, which is not ideal, i'd prefer if this was restylable.

**Comment by willguv** [comment]
@markconroy to review @andybroomfield's code

Should close with the escape key

This will be reviewed by @msayoung and @danchamp

**Comment by danchamp** [comment]
@markconroy Looking good, I haven't finished testing, these are my comments so far:

- The Services button has an `aria-label` of "Toggle Secondary Navigation" - I think "Services" or "Services menu" would be better. Any view @msayoung?
- On Safari the Services button toggles the menu, but doesn't shift focus to the first menu link. I can't see anything obvious that's causing this.

Still thinking about whether we should move focus to the first link of the nav when the button is activated - this is different to the Brighton pattern where the next tab target is the menu when it's toggled.

Out of time, more to follow next week.

**Comment by markconroy** [comment]
@danchamp I had the same issue, but it's because of the default accessibility settings in Safari. https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html

In my case, I had to go to Safari > settings > advanced > "Press tab to highlight each item on a web page"

I've updated the aria-label to "Toggle services menu"

**Comment by danchamp** [comment]
> In my case, I had to go to Safari > settings > advanced > "Press tab to highlight each item on a web page"

It's curious, I've already got that set. Doing more testing just now, will report back shortly.

**Comment by danchamp** [comment]
@markconroy I don't want this to be held up with a minor Safari issue, so happy to approve this and do further testing / raise an issue later.
