### ISSUE TITLE
Replace hard-coded 48rem value with --width-medium variable

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#105]
`variables.css` sets a `--width-medium` variable with a default value of 48rem.

Some components and the grid use a hard-coded value of 48rem for media queries. Using the variable instead will make setting a different breakpoint more straightforward.

**Comment by danchamp** [comment]
TIL: [CSS variables can't currently be used for media queries](https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries).

**Comment by markconroy** [comment]
Yep, it's a right pain. We can use some PostCSS plugin or something to get around it, but can't use a custom property for a media query. The pain is that they are custom "properties" not "variables", so need to be a value in a property:value pairing.
