### ISSUE TITLE
Header search form label has low contrast

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#107]
[Accessibility audit: issue 6](https://docs.google.com/spreadsheets/d/1t8rRIQe_1kogxPBZDKcsbf8YxtEfC9iGJvidkagNSXY/edit#gid=1779042480&range=E7)

<img width="418" alt="Screenshot 2021-07-29 at 16 22 11" src="https://user-images.githubusercontent.com/261421/127519439-7f6fcec3-0060-4de5-af95-0678fef3e3c4.png">

**Comment by markconroy** [comment]
Closed via #113
