### ISSUE TITLE
Release localgov_base as a non-beta tag

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#119]
Hi @markconroy 

We would like to set localgov_base as the default theme in the distribution. 

This will help new councils see the localgov_base rather than the localgov_theme as the starting point and also make it easier for us to bring in localgov_news and any other projects that are built to work best with localgov_base

Would you be willing and able to tag the release @markconroy or should we assign to someone else in the team if you're busy?

CC @markconroy @stephen-cox @danchamp

**Comment by markconroy** [comment]
@finnlewis 

Done: https://github.com/localgovdrupal/localgov_base/releases/tag/1.0.0

**Comment by finnlewis** [comment]
Thanks @markconroy !
