### ISSUE TITLE
Theme refactor frontend: regions

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#12]
# Sample: http://localgov.dev.mark.ie/libraries-leisure-and-culture/z-sports-and-activities

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity

**Comment by markconroy** [comment]
This is ready for review. The header region is already taken care of in another ticket, so just need to test:

- banner - http://localgov.dev.mark.ie
- footer (this has a gazillion regions, hangover from localgov_theme) - http://localgov.dev.mark.ie
- breadcrumbs - http://localgov.dev.mark.ie/adult-health-and-social-care/step-by-step/request-support-adult-step-step/contact-support-team
- sidebar - http://localgov.dev.mark.ie/adult-health-and-social-care/step-by-step/request-support-adult-step-step/contact-support-team

Most of these regions have no styling, just layout (pop a few blocks in footer regions to see they layout ok).

**Comment by msayoung** [comment]
looks good to me, thanks.
