### ISSUE TITLE
Add middle breakpoint and extra fractions to base theme

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#120]
The base theme provides two breakpoints - desktop and mobile - same as the GOV.UK and NHS design systems

Croydon has raised the point [see 13/08](https://docs.google.com/document/d/1PPtq49S68DU6g3rh3X0N4UcyVZZx74wKE7sBUY1ENI8/edit?usp=sharing) that this might not provide enough flexibility for councils. 

New issue for this item:
~Its design system currently includes a 12 column grid, for example~

@markconroy @tom-steel and @willguv agreed to make two changes to the base theme to mitigate this

- [ ] Add a tablet breakpoint and check its effect

New issue for this item

~- [ ] Add classes for extra grid fractions eg 'one eight'~

**Comment by willguv** [comment]
@markconroy can you estimate this (see labels for 1, 2, 3, 5 etc point scores) and do this work? Many thanks!

**Comment by markconroy** [comment]
I'm going to create a spin-off issue for the "add extra fractions" as that's become a little more complex when I was implementing it.

**Comment by markconroy** [comment]
PR for this issue is here: https://github.com/localgovdrupal/localgov_base/pull/127

**Comment by markconroy** [comment]
Mobile
![mobile](https://user-images.githubusercontent.com/2183332/131530767-a8861326-eec6-438d-9e11-9830839c5843.jpg)

Tablet
![tablet](https://user-images.githubusercontent.com/2183332/131530772-8f67bde8-f044-465f-bdd4-91957d9c128d.jpg)

Desktop
![desktop](https://user-images.githubusercontent.com/2183332/131530762-afe78ac0-b89d-47b4-a4bb-45bcc2641de6.jpg)

**Comment by markconroy** [comment]
Closed via #127
