### ISSUE TITLE
Agree on a default pattern for mobile menus

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#121]
The base theme currently shows 'services' and 'menu' buttons on mobile

Croydon and other councils collapse all menu links into one button, often using a hamburger icon and/ or the words 'menu'

The links shown in a mobile menu vary. Croydon, for example, shows the same links as the desktop view. Lambeth shows a reduced set of links.

The front end working group needs to decide on

- [ ] One menu button or two
- [ ] The content of the menu link on a mobile

**Comment by willguv** [comment]
@markconroy I'm wondering whether you've switched to one menu button already?

I just checked https://test.localgovdrupal.org/ and saw this

<img width="745" alt="Screenshot 2021-08-19 at 11 59 01" src="https://user-images.githubusercontent.com/708140/130057546-f1a26df1-5ff3-44e7-a659-468696ccec6b.png">

**Comment by markconroy** [comment]
What's changed?

1. The "menu" button on small screens opens the **search + menu + services list**
2. The "Services" button only shows on large screens
3. Refactoring of the menu regions on small screens for better/more consistent layout
4. A small amount of refactoring for slightly better layout of the menu/search block on large screens

The PR in #136 will make the mobile menu look like this:

![Screenshot 2021-09-11 at 21 50 04](https://user-images.githubusercontent.com/2183332/132961286-c82552cb-3275-4a34-898c-92b748cadbf6.jpg)

**Comment by msayoung** [comment]
@markconroy 
Great plan
Unfortunately when i check out this branch locally the menus won't open, either at desktop or mobile layouts.

**Comment by markconroy** [comment]
Sorry, I had missed a typo in a parameter name.

**Comment by markconroy** [comment]
fixed now

**Comment by markconroy** [comment]
Closed via PR #136
