### ISSUE TITLE
Typo in the Readme

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#125]
Instead of creating documentation for the theme and storing it in a wiki or something else that is likely to not be updated, we have written **details** comments inline with the code. This should make it easier to know exactly what code block any specific documentation item refers to.

**Simple** run npm install to get the necessary packages, then run npm start to scan the files and fix any issues.

**Comment by drinkynet** [comment]
There are typos in the opening paragraph too:

> This theme was developed with scalability and **easy** of use in mind. That means, the theme should be a very good starting point for any website using the LocalGov Drupal distribution, and it **provide** an easy way to be customised out of the box.

Suggested alternate wording for it:

> We developed this theme with scalability, ease of use, and ease of customisation in mind. Making this base theme a great start point for any website using the LocalGov Drupal distribution.

**Comment by markconroy** [comment]
Fixed in `a33f384`
