### ISSUE TITLE
Safari outlines the main content

### ISSUE THREAD

**Issue by drinkynet** [localgovdrupal/localgov_base#130]
Safari (iOS and Mac) outlines the main element when its clicked or tapped on as [it has a tabindex](https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/layout/page.html.twig#L103). It may need outline:none applying to it to hide it.

![iOS safari outline on main element](https://user-images.githubusercontent.com/6780886/131735287-e4bd7bf4-e6c4-4dd4-9db6-e609e7fd095b.png)
![MacOS safari outline on main element](https://user-images.githubusercontent.com/6780886/131735482-36ee9161-477e-448a-8dc2-21ee19b35044.png)

**Comment by finnlewis** [comment]
@markconroy noticed in our OxDUG meetup!

**Comment by markconroy** [comment]
Here's a PR for this issue 
https://github.com/localgovdrupal/localgov_base/pull/131

**Comment by danchamp** [comment]
Nice catch, thanks @drinkynet

**Comment by markconroy** [comment]
Closed by #131
