### ISSUE TITLE
Subsite page banner image floats left

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#135]
Hi @markconroy 

On this subsite page: https://demo.localgovdrupal.org/bereavement-services/choosing-memorial

The banner image could do with central alignment of some sort. 

![image](https://user-images.githubusercontent.com/326588/132862376-5ba16a6a-13b3-4222-8119-f8ecb20241f6.png)

**Comment by markconroy** [comment]
Thanks @finnlewis 

I noticed that last week, but forgot to create an issue for it. I think that banner is supposed to go full width, rather than just centered. I'll get that done next week.
