### ISSUE TITLE
 Theme refactor frontend: localgov_services_sub_landing_page 

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#15]
- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity 

Estimate: 13

**Comment by markconroy** [comment]
This is ready for review. Files to consider are:

- `field/field--paragraph--topic-list-links--topic-list-builder.html.twig`
- - This creates the listing of teasers
- - Note: this is the template that renders the icon beside the teaser. That is not part of the teaser template.

**Comment by cjstevens78** [comment]
I have reviewed - all good. Thanks Chris

**Comment by msayoung** [comment]
![image](https://user-images.githubusercontent.com/3852805/122406088-7de33700-cf78-11eb-90ac-b0c1244cefed.png)
there seems to be a rogue Read more on the sub-landing page http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship/marriage-and-civil-partnerships

**Comment by msayoung** [comment]
Also there's a jump between H1 to H3 on the sub-landing pages. http://localgov.dev.mark.ie/libraries-leisure-and-culture/z-sports-and-activities . 
Potential solution:
- An H2 before the teasers eg. "In this section"

![image](https://user-images.githubusercontent.com/3852805/122429762-edfab880-cf8a-11eb-885f-ab106d73b92e.png)

**Comment by markconroy** [comment]
Thanks @msayoung 

That extra "More" is fixed (I had forgotten to comment back in the `{% if ... %}`.

The h2 is taken care of by the "Title" field in that component if it's filled in. I've filled it in in that sample node now.
