### ISSUE TITLE
CSS aggregation breaks subthemes

### ISSUE THREAD

**Issue by graham-web** [localgovdrupal/localgov_base#153]
Enabling Drupal's 'Aggregate CSS Files' option while using a child theme of localgov_base makes all of the localgov_base styling disappear.

Steps to reproduce:
1. Generate child theme via `scripts/create_subtheme.sh`
2. Enable and set default child theme - this looks OK
3. Switch on CSS aggregation

This should have no effect visually, but causes practically all styling to disappear:

![Screenshot 2021-10-19 at 09 38 51](https://user-images.githubusercontent.com/47783560/137874480-89b1e3ca-4f61-4519-828d-cfa16a54363e.png)

(NB - default localgov dev setup may force CSS preprocess off via `settings.lando.php`, which masks the issue!)

**Comment by graham-web** [comment]
I tried removing the reference to `localgov_base/global` from `localgov_base.theme` and adding it to my subtheme's `foo.info.yaml`, but this didn't help.

Removing the reference to the `subtheme/variables` library **does** resolve the issue, but obviously hinders theming!

**Comment by graham-web** [comment]
This turned out to be a manifestation of a [long-standing Drupal core bug around aggregation of @import rules](https://www.drupal.org/project/drupal/issues/2936067)

The google fonts URL included in the default subtheme variables.css has semicolons, which triggers the bug and mangles all the rest of the CSS in that aggregation group.

A fix was committed to the Drupal core 9.2.x branch just last week, so should appear in the next core release. Tested, and resolves this issue for me, so no need to change anything here I guess!

**Comment by markconroy** [comment]
Thanks very much for ereporting and debugging this for us @graham-web .

I think to be on the safe side, I'll remove the @import in the subtheme template. There's already a note in that file that using this is not a best practice (from a performance point of view), and we can add it via the html.html.twig file, like we say it should be done.

Thanks.

**Comment by markconroy** [comment]
Re-opening, so I can work on this.

**Comment by markconroy** [comment]
Hi @graham-web 

Here's a PR to fix this issue - https://github.com/localgovdrupal/localgov_base/pull/158

Would you (or anyone else perhaps) please test it. You just need to create a subtheme using the subtheme script, and then see that the site works even with CSS aggregation turned on.

Thanks.

**Comment by justinepocock** [comment]
I can take a look

**Comment by justinepocock** [comment]
This works fine. It's good to have the sample library example too.

**Comment by markconroy** [comment]
Thanks @justinepocock 

This is now fixed and released in 1.2.2 of localgov_base.
