### ISSUE TITLE
 Theme refactor frontend: localgov_services_node_page

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#16]
# Sample: http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship/registering-birth

- [ ] Put the templates in place in the theme
- [ ] Move styling into localgov_base theme.
- [ ] confirm feature parity 

Estimate: 13

**Comment by markconroy** [comment]
I think this is ready to test now. Files to consider:

- `block/services-cta-block.html.twig`
- - This creates the listing of action/information tabs at the top of the page
- Feel free to test the styles in the WYSIWYG for alerts and call outs as well.

**Comment by cjstevens78** [comment]
I have reviewed this - all good - alerts are all good too. Thanks Chris

**Comment by msayoung** [comment]
All good, but I wonder if we want to limit the width of content like this to 2/3 at wide screens to keep the line length readable?

**Comment by markconroy** [comment]
That's simple to do if we decide to. @msayoung do you want to create a new issue for that discussion, and we'll mark this as "reviewer approved"?

**Comment by msayoung** [comment]
Sure, go ahead - new issue here: https://github.com/localgovdrupal/localgov_base/issues/51
