### ISSUE TITLE
Directory areas should pick up colours from base theme pallet

### ISSUE THREAD

**Issue by tom-steel** [localgovdrupal/localgov_base#160]
When a directory item has an area, the outline of the area is a light blue colour, which is not in use anywhere else on the site.

Can the styling pick up a colour and tint from an existing colour that's already been defined in the theme

**Example URL**
[demo.localgovdrupal.org/national-parks-uk](https://demo.localgovdrupal.org/national-parks-uk?f%5B0%5D=localgov_directories_facets%3A8)

**Example screenshot**
![image](https://user-images.githubusercontent.com/74607288/145243794-e4d5b7d4-e2f9-40a4-9056-f17eda201f2e.png)

**Comment by MattOz-CDS** [comment]
My understanding is that the default stroke colour for a polygon borders is provided by leaflet.js. [This](https://gis.stackexchange.com/questions/228214/how-to-give-color-to-polygon-border-in-leaflet-map) post over at Stack Exchange suggests a way in which it can be overridden. 

My questions would be, should we follow the Stack Exchange example and create a Drupal behaviour within in the localgov base theme's JS that imports a variable from the localgov base theme to use as the stroke colour? Is there an alternative way of doing this? 

Please share your thoughts.

Thanks

**Comment by markconroy** [comment]
@tom-steel do you want to test this attached PR?

Turns out this is very simple for us. The stroke colour is set inline in the SVG via the `stroke` attribute. So I just created a CSS variable `--leaflet-map-outline-stroke-colour` in the base theme (set to the same blue as the current default so no sites break), and now any theme can set that variable to whatever they want.

**Comment by MattOz-CDS** [comment]
Thanks @markconroy. Nicely done and much appreciated.

**Comment by tom-steel** [comment]
> @tom-steel do you want to test this attached PR?
> 
> Turns out this is very simple for us. The stroke colour is set inline in the SVG via the `stroke` attribute. So I just created a CSS variable `--leaflet-map-outline-stroke-colour` in the base theme (set to the same blue as the current default so no sites break), and now any theme can set that variable to whatever they want.

Will that variable automatically override the hard coded stroke styling in leaflet.js then? No other JS needed?

**Comment by markconroy** [comment]
Yes, that's exactly what it does. I set it to the same colour that is currently used by leaflet so anyone currently using it will have no effect on their sites unless they specifically choose to set a different colour.

Let me know once it's tested and we can get it merged and deployed.
