### ISSUE TITLE
Add nvmrc, stylelint, etc to subtheme generator, so subthemes can auto follow drupal coding standards

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#164]

**Comment by justinepocock** [comment]
I created a new theme, enabled it, made some questionable css and ran npm install and npm start - style linter did its job. 

I think maybe the readme section could be copied or a new one generated to include the parts about the coding standards. 

This works.

**Comment by markconroy** [comment]
Closed by #169
