### ISSUE TITLE
Improve layout of header toggle buttons

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#165]
The header toggle button layout (text with icon beside it) is a little off. See here:
![current](https://user-images.githubusercontent.com/2183332/150111494-68a40722-fea9-4ebf-8ceb-3d7d008f0e2b.jpg)

Let's change the CSS slightly to have a better alignment, see here:
![proposed](https://user-images.githubusercontent.com/2183332/150111498-f12efaf3-24d7-4424-8cf6-42e6f0eb4518.jpg)

**Comment by justinepocock** [comment]
This fix works well in a bunch of browsers and breakpoints. Thanks for sorting this niggle out!

**Comment by willguv** [comment]
Hi @markconroy, this is great - thank you. 

Can I be a bit cheeky and suggest another possible fix? It's always bugged me that Services, Docs, Github links and the search box don't sit on a line together, and are aligned middle. [Like Cumbria](https://new.cumbria.gov.uk/births-deaths-marriages-and-ceremonies).

Is there any reason for this? And is it an easy fix?

Cheers

**Comment by markconroy** [comment]
@willguv We can make it look like this with a relatively small amount of work. Does this look okay?

![Screenshot 2022-01-19 at 15 48 56](https://user-images.githubusercontent.com/2183332/150166018-877559f6-fa21-4202-bf93-fdcf7e160dd2.jpg)

**Comment by markconroy** [comment]
I'm going to merge this issue, and we'll open a new on if we are in agreement that we will do that new header layout.

**Comment by willguv** [comment]
@markconroy the minor changes you suggested are perfect - please do open a new issue
