### ISSUE TITLE
Improve layout of header menu/search/buttons section

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#167]
Currently, our default header looks like this:

![Screenshot 2022-01-20 at 09 51 40](https://user-images.githubusercontent.com/2183332/150315105-1ad8450f-2718-4241-948e-897c3ebfe0f0.jpg)

Let's make it look like this:

![150166018-877559f6-fa21-4202-bf93-fdcf7e160dd2](https://user-images.githubusercontent.com/2183332/150315039-1fadbd31-2d2f-4aa7-be40-f84586cd53f3.jpg)

**Comment by justinepocock** [comment]
This works well and is an improvement to the alignment of the header items. 

Two small points, that might well be new tickets or not even worth LGD considering. 

1. On tablet sized things the search sits next to the links which is ok but having it to the right, underneath the services button might be nicer. Maybe this is too much styling for a base theme?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/638213/150350904-f461d446-1744-4423-9415-657d3147e489.png">

2. The height of the search button on hover for me doesn't match the height of the input field. 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/638213/150351238-872081ae-980d-4d56-ab46-e1098af4571c.png">

**Comment by markconroy** [comment]
Thanks @justinepocock 

I'll merge what we have, since it's an improvement, and we can create follow-ups for the your suggestions.

**Comment by markconroy** [comment]
Closed via PR #168
