### ISSUE TITLE
Consider supporting the ModernGov 'reverse CMS' template out of the box

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#174]
Coming from https://github.com/localgovdrupal/localgov_moderngov_tpl/pull/1

It would be good to support this by default, which maybe needs us to add the template to the localgov_base theme.

**Comment by finnlewis** [comment]
@Adnan-cds does this make sense? Will it all hang together nicely if we have the right twig template in the localgov_base theme?

**Comment by markconroy** [comment]
Do we have a test instance of Modern Gov that we can use to test these templates against?

**Comment by Adnan-cds** [comment]
> Will it all hang together nicely if we have the right twig template in the localgov_base theme?

Hi Finn, yeah, that should do.

> Do we have a test instance of Modern Gov that we can use to test these templates against?

Hi Mark, I will try to come up with some setup instructions for you.  Hopefully within a day or so.

**Comment by Adnan-cds** [comment]
- First, install the new code:
```
$ composer require localgovdrupal/localgov_moderngov_tpl:dev-feature/first-cut
$ drush pm:enable --yes localgov_moderngov_tpl
```
- Next login as site admin.
- Create a new node or pick an existing node that you want to use as the ModernGov page.  Note down its node id.
- Save the above node id from /admin/config/content/moderngov/settings.
- Log out a load that node.
- If the test site is reachable over the web then you can test it at ModernGov's [test site](https://reversecms.moderngov.co.uk/).

**Comment by markconroy** [comment]
Thanks very much @Adnan-cds
