### ISSUE TITLE
Align icons in status messages better.

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#176]
Current:
![Screenshot 2022-01-28 at 14 59 24](https://user-images.githubusercontent.com/2183332/151569483-fa66d340-ff96-4f2a-b591-54494d0d87a9.jpg)

With patch:
![Screenshot 2022-01-28 at 14 58 40](https://user-images.githubusercontent.com/2183332/151569492-03b8e604-e246-416b-a117-dc80d31c307c.jpg)

**Comment by justinepocock** [comment]
As we say in bristol, Cheers Drive, this is gurt lush. 

Or Thanks Sir, this works really well.
