### ISSUE TITLE
Fix issue with class naming on forms radios

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_base#178]
Turns out the class being used to target radios for drupal forms actually uses the 'name' given which is itself defined by the 'title' chosen by the editor. So the class used '.form-item-radios' only works if the radio button set has a title of 'radios' .. so for example if my new set was called 'Chris Test' the class would change to '.form-item-chris-test' ... obviously this wont do so it needs to be changed to use a constant class thats specific to radios.

**Comment by markconroy** [comment]
Thanks very much for this @cjstevens78 

I'll get it fixed asap.

**Comment by markconroy** [comment]
Oh, I see you have a PR already. Magic. Thanks.

**Comment by markconroy** [comment]
Merged. Thanks very much @cjstevens78
