### ISSUE TITLE
Accessibility issue on the Guide page - dashes vs list items.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#18]
When creating a guide overview page, the content designer has the option to select numbers, dashes or bullets. 

There might be an accessibility issue with this. 

@markconroy could you elaborate on this?

@andybroomfield can you also tell us how Brighton and Hove are using these?

**Comment by markconroy** [comment]
Here's an article elaborating on this
https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

**Comment by cjstevens78** [comment]
+1 to remove

**Comment by andybroomfield** [comment]
Not seeing any use of dashes in BHCC databases.

**Comment by markconroy** [comment]
@willguv it might be good to ask at the product group if anyone is using the dashes and tell them to change them to select bullets instead.

Then we can more easily remove that field option.

**Comment by willguv** [comment]
@markconroy I think only Brighton is aware this option exists. Everyone else is using Step by Step for the same job

@andybroomfield do you have a view on the use of dashes? Thanks

**Comment by finnlewis** [comment]
@willguv I think @andybroomfield already commented above: "Not seeing any use of dashes in BHCC databases" :)

**Comment by willguv** [comment]
Yes, sorry @finnlewis and @andybroomfield 

@markconroy I think dashes can be safely dropped

**Comment by markconroy** [comment]
Thanks @willguv 

I have this removed from the templates and CSS from the new base theme.

**Comment by danchamp** [comment]
Closed by https://github.com/localgovdrupal/localgov_guides/issues/62
