### ISSUE TITLE
Theme refactor frontend: localgov_step_by_step

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#2]
# Sample - http://localgov.dev.mark.ie/adult-health-and-social-care/step-by-step/request-support-adult-step-step

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity 

Estimate: 5

**Comment by ekes** [comment]
Wasn't this one of the modules where it made sense to impose some theming as it's functionality?

**Comment by andybroomfield** [comment]
Yeah, some templates are going to be needed in this module for various views, otherwise it will be broken if just installing this module.

**Comment by finnlewis** [comment]
@markconroy you mentioned at stand-up that this might change direction rather than refactoring all the things. Could you perhaps elaborate here for the record?

**Comment by markconroy** [comment]
Notes on what is blocking this are available in this issue
https://github.com/localgovdrupal/localgov_step_by_step/issues/36

**Comment by tom-steel** [comment]
All looking smashing @markconroy - can only spot two quirks:
- The step by step overview page has text running the full width when it needs to be constrained to the content body width
- On each step page, there doesn't need to be the step heading above the list of steps on the right.

**Comment by msayoung** [comment]
Nice, thanks. 
Is it possible to also constrain the steps below the content on the step overview page ? 
![image](https://user-images.githubusercontent.com/3852805/124127242-670e0b80-da73-11eb-9d61-84c863c47366.png)

I think @tom-steel 's second point was that we don't need the repeated block of "Part of ... " title at the top of the sidebar on the step page:
![image](https://user-images.githubusercontent.com/3852805/124127064-3332e600-da73-11eb-8d1e-f7313f95465b.png)

Could you add an aria-label to the previous / next Step nav element please:
`aria-label="Step by step"`
Thanks

**Comment by markconroy** [comment]
Hi @msayoung 

1. The nav block is now set to a max of 48rem (768px)
2. The "Part of ..." is part of the view config (placed in the view header). If we want that removed, we'll need to create an issue in the step-by-step repo (and be aware that might affect current sites that use it)
3. The nav element now has the aria label you requested

**Comment by msayoung** [comment]
> The "Part of ..." is part of the view config (placed in the view header).

Oh yes, so it is. There's a naughty little `display:none` in the localgov_theme

Thanks for the other things. 
@danchamp you have anything to add?

**Comment by danchamp** [comment]
@markconroy @msayoung Looks good, nothing to add thanks.
