### ISSUE TITLE
Theme Refactor: Guide Page

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#21]
# Sample: http://localgov.dev.mark.ie/adult-health-and-social-care/travel-passes-and-support/blue-badges/blue-badges-organisations

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity

**Comment by markconroy** [comment]
This is ready for review. Files to consider include:

- `content/node--localgov-guides-page--full.html.twig`
- - Full node template for a guide page.
- - the main point of this seems to be to set the node title in a `h2`. Maybe we could come up with a simpler way.

**Comment by cjstevens78** [comment]
- Header role
- Dashes in the nav
- Grid layout
- Next and Prev buttons have the same class
- Nav items all have active class

Full comments see the guide overview page ... https://github.com/localgovdrupal/localgov_base/issues/20

**Comment by markconroy** [comment]
This should all be fixed now after the work in #20

**Comment by msayoung** [comment]
looks good to me
