### ISSUE TITLE
Skip to main content link bypasses important content

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#23]
As per localgovdrupal/localgov_theme#149

**Comment by markconroy** [comment]
Hi @danchamp 

I think this is a larger issue that needs to be solved further up the chain. Where we currently jump to is the same as where the current localgov_theme jumps to.

It will be hard to get around this without a discussion about how the current set up works in terms of blocks and block placements.

One thing we could do is just move the `<main>` element further up the DOM but I'm not sure if all the other blocks placed above it are doing that for a specific reason.

**Comment by danchamp** [comment]
Thanks @markconroy. Moving `<main>` up the DOM would be an improvement for semantics and accessibility.

If there are issues doing that another option would be to put an id on `content-top` and use that as the target for the skip link if it's present, otherwise `main-content`.

I'd closed this for further reflection but have re-opened it because we need to do something.

**Comment by markconroy** [comment]
See PR https://github.com/localgovdrupal/localgov_base/pull/59

**Comment by danchamp** [comment]
@markconroy This is better, although it results in `<main>` containing too much ancillary content for me (including all alerts and messages). Would it be viable to move the opening tag below page.banner, page.breadcrumbs, and page.messages?

I.e. `<main>` wrapping everything from `page.content_top` to `page.content_bottom` inclusive, closing just before the `#main-content` `<div>`, and keeping the skip link target id?

**Comment by markconroy** [comment]
That's moved now @danchamp

**Comment by msayoung** [comment]
Loads better, thanks
I think the Guide overview page and event page are a little awry, with the skip link behaving differently to the rest of the pages
On those pages the breadcrumb and alert banners are still contained within the main.

**Comment by markconroy** [comment]
@msayoung 

That's not happening for me. It might have been a cache issue or just look like the page doesn't scroll all the way down simply because there's not enough content on the page for it to scroll to.
