### ISSUE TITLE
Block won't appear

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_base#234]
I've had an issue today where a block I've created would appear with the title displayed, but hid when the title was hidden, or would display just fine alongside another block in the same region, regardless of if the title was set to display or not.

I've tracked this down to the code in localgov_base_preprocess_page() which renders the regions and strips out HTML tags to determine if the region is empty or not. Currently it strips out all tags, which means that blocks whose content is entirely HTML will not display.

I've fixed this by adding exceptions to the stip_tags call for input and form, which lets my block display as expected.

**Comment by markconroy** [comment]
This is fixed from PR #235
