### ISSUE TITLE
Theme Re-factor Banner Secondary

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#24]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme - No styling needed
- [x] confirm feature parity 

![Screenshot 2021-06-15 at 11 30 22](https://user-images.githubusercontent.com/2183332/122038042-1c329980-cdcd-11eb-9ae5-9d01923a35c0.jpg)

**Comment by markconroy** [comment]
Branch 1.x

This is ready for review. Files to look at:

- `paragraphs/paragraph--localgov-banner-secondary.html.twig`

There are no CSS changes needed, since the only field is the image field and that's a 100% image.

**Comment by danchamp** [comment]
Looks good @markconroy, no issue here.
