### ISSUE TITLE
Theme Re-factor: featured Subsite

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#26]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme
- [x] confirm feature parity (we actually have more features, given our new CSS)

![Screenshot 2021-06-15 at 11 29 09](https://user-images.githubusercontent.com/2183332/122037909-f7d6bd00-cdcc-11eb-8e05-58f18b7d5d5d.jpg)

**Comment by markconroy** [comment]
Branch 1.x.

Ready for Review. Files to consider:

- `paragraphs/paragraph--localgov-featured-subsite.html.twig`
-  `css/components/featured-subsite.css`
- -  `css/components/featured-subsite.ie11.css`

**Comment by msayoung** [comment]
looks good. 
do we need another issue logged somewhere to review the images styles set up for this?

**Comment by markconroy** [comment]
Hi @msayoung 

I'm not sure. If we need another issue for that, I think it should go in the subsite repo issue queue, not the base theme.

**Comment by danchamp** [comment]
@markconroy This is good for me. There is an issue with the labels being visually hidden and therefore announced to screen readers, I've raised this in subsites: https://github.com/localgovdrupal/localgov_paragraphs/issues/132
