### ISSUE TITLE
Theme Re-factor: Video Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#30]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/video-page-key-contact

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme - NONE needed
[x] confirm feature parity

**Comment by markconroy** [comment]
I'm going to say this is ready for review, but there is an issue on the subsites repo that ought to be addressed: it's causing the videos to be displayed at 200px wide.

https://github.com/localgovdrupal/localgov_subsites/issues/30

Files to check:
- `templates/paragraph--localgov-video.html.twig`

**Comment by markconroy** [comment]
See PR https://github.com/localgovdrupal/localgov_base/pull/31

**Comment by msayoung** [comment]
looks fine to me
