### ISSUE TITLE
Sticky footer

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#301]

**Comment by willguv** [comment]
@msayoung I'm not sure if I've ever seen a sticky footer

Thinking a sticky header might be useful, but parking for now

**Comment by msayoung** [comment]
A sticky footer pattern is one where the footer of your page "sticks" to the bottom of the viewport in cases where the content is shorter than the viewport height.

https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers

You'll have seen them without noticing. It avoids having the footer half way up the browser if there's not much content on the page.

**Comment by willguv** [comment]
@msayoung I’ve never heard it called that!

Yes this definitely needs addressing, will move it
