### ISSUE TITLE
sticky header

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#303]

**Comment by markconroy** [comment]
This is a great idea. 

I reckon we should add it on the theme setting pages so sites can easily turn it on/off as part of the site config.

Maybe also an option for it to be

1. Not sticky
2. Sticky
3. Visible when you scroll up page

Whatcha think?

**Comment by msayoung** [comment]
I think it's a good idea, but I think its less important than some other things, as if people feel really passionate about it they can create a custom theme to do it. 

But yes, I think we should add the feature at some point.

**Comment by markconroy** [comment]
PR available for this here: https://github.com/localgovdrupal/localgov_base/pull/569

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
