### ISSUE TITLE
Missing container tags for page regions

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_base#313]
We recently merged in the latest base theme and noticed a lot of design inconsistencies caused by a missing set of container div's surrounding 'lgd-region' blocks. Looking at what might have caused this I think it may be related to the reworking of the page.html.twig file (templates/layout/page.html.twig). This change: https://github.com/localgovdrupal/localgov_base/pull/304/commits/3a70d08fcd9e48fb0ec8a3b4404a7520cdf0608d leaves a final conditional (line 166) which outputs the page content without any tags around it. 

In the page source I would expect to see:
`<div class="lgd-container"><div class="lgd-row"><div class="lgd-row__full"><div class="padding-horizontal"><div class="lgd-region"></div></div></div></div></div>`

but instead im just seeing:

`<div class="lgd-region"></div>`

<img width="732" alt="Screenshot 2022-10-27 at 12 21 03" src="https://user-images.githubusercontent.com/11304107/198307496-dac4d86d-a01f-4152-aa6e-a7b53b52b501.png">

**Comment by markconroy** [comment]
We have deliberatly set the page content region to have no container div with that commit, so then we can have full page layouts for paragraphs fields. 

Each individual node template should look after the container, with `node--full.html.twig` being the fallback/catch-all if not using a custom template for a content type.

Is it working like that for you, or is there something else I am missing?

**Comment by cjstevens78** [comment]
Hi Mark, this change breaks the layout across multiple pages on our site and is preventing us from updating to the latest version of localgov_base. Are you able to confirm what changes we need to be making in order to restore these regions to how they were presented before? Thanks Chris

**Comment by msayoung** [comment]
Hi @cjstevens78 and @Adnan-cds 

I've looked into this and have found cause of the issues, if not the solution. 

1. [Edited] In your .theme file you are adding the .lgd-row__two-thirds class to the guide page `<article>`. This is breaking the layout, so I suggest removing this, and instead adding a div inside the div.lgd-container.padding-horizontal with this class. I _think_ this should maintain your current layout.  

2. The issue with Service Landing page - in your override for the services landing page template (https://github.com/localgovdrupal/localgov_base_croydon/blob/1.x/templates/content/node--localgov-services-landing--full.html.twig) - if you add the divs in lines 43-47 [of node-localgov-services-landing--full in the base theme](https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/content/node--localgov-services-landing--full.html.twig#L43) to your theme, that should solve the issue.

**Comment by cjstevens78** [comment]
@msayoung @Adnan-cds Hi Maria, many thanks for looking into this, we have implemented the changes as advised - all good now.
