### ISSUE TITLE
'Site slogan' toggle functionality is missing in site branding block

### ISSUE THREAD

**Issue by clearspotmedia** [localgovdrupal/localgov_base#317]
As a CMS user on a fresh install of base and scarfolk, the 'Site slogan' toggle functionality has no effect.
/admin/structure/block/manage/localgov_sitebranding_scarfolk?destination=/node

You would expect it to appear in the header next to the logo.

I tested adding the functionality to this template (scarfolk just for this example):
/localgov-project/web/themes/contrib/localgov_scarfolk/templates/block/block--system-branding-block.html.twig

`   {% if site_slogan %}
          <div class="branding__item branding__item--slogan">
          {{ site_slogan }}
          </div>
      {% endif %}`

For a non technical person it isn't clear why the slogan doesn't appear.
If this is activated there is some styling work to do to make the logo and slogan appear alongside each other.

First issue raised, hope I've done it correctly, and it's helpful

**Comment by markconroy** [comment]
Thanks for posting this issue. 

In the original base theme - based on the sites that had been using the old base theme - there was no slogan present.  But you are probably right that we should support it if it's there (or remove it).

**Comment by clearspotmedia** [comment]
No problem Mark. I think this will be useful for micro sites, where we want to label a site such as 'Design system' with our service label pattern https://www.croydon.gov.uk/design-and-content-guidelines/resources/header-and-footer/service-label

**Comment by markconroy** [comment]
It works for microsites already. So this change will only be affecting the `localgov_base` theme.

**Comment by markconroy** [comment]
Hi @clearspotmedia 

I've created a PR for this #331 

Can you test it and tell me if it's working for you. When I add a site slogan the variable remains empty, but the code looks like it should be working.

**Comment by clearspotmedia** [comment]
Thanks @markconroy and thanks for clarifying regarding micro sites.
I tested this on my local install and the slogan now pulls in fine.

One last thing could we look at moving **.branding__item--slogan**  div inside **.branding** div wrapper?

That way flex classes can be applied to **.branding** wrapper to position the two items side by side.
At the moment I would have to apply flex further up to the parent div, it's not ideal.

**Comment by clearspotmedia** [comment]
I'm new to github, forgive me if I'm making suggestions in the wrong way.
As per last comment the twig template with the two branding items inside **.branding** wrapper below:

`{% extends "block.html.twig" %}
{#
/**
 * @file
 * Theme override for a branding block.
 *
 * Each branding element variable (logo, name, slogan) is only available if
 * enabled in the block configuration.
 *
 * Available variables:
 * - site_logo: Logo for site as defined in Appearance or theme settings.
 * - site_name: Name for site as defined in Site information settings.
 * - site_slogan: Slogan for site as defined in Site information settings.
 */
#}

{% block content %}
	{% if site_logo %}
		<div class="branding">
			<div class="branding__item branding__item--logo">
				<a href="{{ path('<front>') }}" rel="home" class="branding__logo">
					<img src="{{ site_logo }}" alt="{{ site_name ? site_name : 'Home'|t }}"/>
				</a>
			</div>
		{% endif %}
		{% if site_slogan %}
			<div class="branding__item branding__item--slogan">
				{{ site_slogan }}
			</div>
		{% endif %}
	</div>
{% endblock %}`

**Comment by finnlewis** [comment]
Just having a quick look at the pull request here: https://github.com/localgovdrupal/localgov_base/pull/331

Is there any risk that someone might have a slogan set and this would suddenly reveal the slogan in the header?

**Comment by finnlewis** [comment]
@andybroomfield might have time to review the pull request too!

**Comment by clearspotmedia** [comment]
@finnlewis hi yes I guess that is a risk, they would have to have both a text value defined in the site settings, and the slogan toggled on in the block for anything to appear
