### ISSUE TITLE
New page_section without width displays wider than content

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#320]
If I have a page_section with no width set:
![image](https://user-images.githubusercontent.com/3852805/197553775-3ee650ae-7f57-437d-875f-211cee2abbb0.png)
it displays wider than the main area (eg  H1)

![image](https://user-images.githubusercontent.com/3852805/197553927-76062582-1bd1-4a73-a45c-b16c40ce58dd.png)

I would expect it to default to be inline.

**Comment by markconroy** [comment]
Me too!

I guess we could add a `padding-horizontal` class to it? Would that be enough?

**Comment by msayoung** [comment]
probably the same classes as the contained-content ?

**Comment by markconroy** [comment]
Exactly! That's what I thought we had.
