### ISSUE TITLE
Theme Re-factor: Box Links Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#34]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

**Comment by markconroy** [comment]
See PR: https://github.com/localgovdrupal/localgov_base/pull/44

**Comment by msayoung** [comment]
@markconroy  to confirm we're looking at these guys?
![image](https://user-images.githubusercontent.com/3852805/122568170-6459f200-d041-11eb-810b-32208665f518.png)
Looks good. 

Have we lost the external link icon?

**Comment by markconroy** [comment]
I had presumed that was coming from extlink module or somewhere, not the theme. I'll create an issue for that.
