### ISSUE TITLE
Layout on "Preview Link" share page

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#343]
When you go to "Preview Link", the page with the link to share looks a bit odd. For guide pages, the buttons also come right up against the previous/next navigation buttons.

![image](https://user-images.githubusercontent.com/19519457/211620902-2bdbef66-e9be-4275-8880-99568f4c3b3d.png)

**Comment by keelanfh** [comment]
These buttons are still very close, is there anything we can do about that?

![image](https://user-images.githubusercontent.com/19519457/213752537-6163e4e0-f92b-46ff-892e-14d522f3e873.png)

**Comment by andybroomfield** [comment]
Hmm, feels like this should be an admin theme route, although I see there is a PR in the base theme to at least fix the styling.

**Comment by markconroy** [comment]
That's updated now @keelanfh 

![Screenshot 2023-01-23 at 08 20 26](https://user-images.githubusercontent.com/2183332/213993659-3a96649e-20cd-4ee2-9a59-9d1d1aed09f7.jpg)

Can you test the MR again please?
