### ISSUE TITLE
Stable theme has been removed from core

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_base#344]
As described here: https://www.drupal.org/node/3309392. Stable is deprecated in Drupal 9 and removed in Drupal 10 (https://www.drupal.org/node/3309392)

The new stable base theme is called `stable9`. The alternatives are to used the `starterkit_theme` or copy everything required from the `stable` base theme and not have a base theme.

**Comment by stephen-cox** [comment]
This needs to be resolved as part of the Drupal 10 upgrade #333

**Comment by markconroy** [comment]
Thanks Stephen. We also have the option of using Stable from contrib if we wanted to make sure we have the same base theme as the current theme is using.

I'd be against using starterkit_theme, as that's specifically a starterkit to get going with, rather than a base them.
