### ISSUE TITLE
Let's stop explicitely supporting IE11 for the frontend theme

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#349]
- We have ie11 CSS files in our codebase. Keeping them up-to-date when editing the theme is cumbersome. 
- If you look at an LGD site in IE11, it's pretty ugly (because it uses the default fallback colours rather than the new colours from your custom theme).
- Since no one has complained about "our site uses ugly colours in IE11" I'm left thinking of two possibilities
- - People really like our IE11 design
- - No one has visited our LGD sites in IE11 (or maybe they are just used to sites looking ugly)
- If the latter is true, we are maintaining something that is not of value to our users
- Debugging takes longer with IE11 being supported, because everytime you want to comment out some code, you may also need to comment out the IE11 code). This is especially annoying when working in the inspector.
- If we drop IE11 support, we can rewrite our grid system in grid instead of flexbox and this will have the benefit of removing many of the annoyances of 8px left/right margins we have that mean things almost line up perfectly with each other, but not fully. 
- If we keep supporting IE11, we have to keep using part of JS that are no modern or use polyfills instead or compilers, etc, rather than writing ES6+ JS.
- If we drop IE11 support, we will have about 30% less code in localgov_base
- We'll be dropping IE11 support soon in any case when we move to D10, so I'm proposing we do so now instead.

**Comment by keelanfh** [comment]
+1 for this from Essex, in general.

Our analytics over the last 30 days shows <0.002% of our users using IE - 5 visitors out of 293,000.

If the stats on caniuse.com are accurate, I'd guess we exclude about 500x as many users from accessing our site entirely through not supporting anything less than TLS v1.2 - as does gov.uk.

Question @markconroy - would dropping support mean that this content would be invisible/obscured in IE11? Or just styling wouldn't be as we expect? It looks like GOV.UK dropped support to a 'functional' level: https://github.com/alphagov/govuk-frontend/discussions/2607. I'm not too bothered either way, just curious.

**Comment by markconroy** [comment]
It just means the styling wouldn't be as expected. You'd get some styling if IE11 can use those properties, so we wouldn't be actively trying to break things, just not worrying about them in the first place.

**Comment by finnlewis** [comment]
This is interesting: 

https://technology.blog.gov.uk/2022/06/16/service-manual-testing-requirement-changes-for-internet-explorer-11/

Let's ask our councils for data to hopefully support this decision. 

@andybroomfield @Adnan-cds @Boosmith do you have stats on how many IE11 users visit your main websites?

**Comment by keelanfh** [comment]
> It just means the styling wouldn't be as expected. You'd get some styling if IE11 can use those properties, so we wouldn't be actively trying to break things, just not worrying about them in the first place.

in that case I am even more in favour!

**Comment by andybroomfield** [comment]
BHCC does not actively support IE anymore:

![browserling-screenshot](https://user-images.githubusercontent.com/1467480/213883913-86e4c31b-e3a4-4011-ad92-8d25a8e285ff.png)

IE is only supported as part of Edge on council laptops.

We still keep the Polyfills in place for IE users, and give them a fallback grid, we just don't try to actively make the design work anymore.

Will have to check on the statistics, though it was always quite small at this point.

That said, this would be a drastic change for the base theme to withdraw IE support, so might be one for a major version bump. 

I don't believe IE is supported in Drupal 10, so formally dropping it in localgov 3 / localgov_base 2 could be a better target.

**Comment by markconroy** [comment]
> I don't believe IE is supported in Drupal 10, so formally dropping it in localgov 3 / localgov_base 2 could be a better target.

That's correct. I'd just like to drop support from now rather than waiting on us moving to D10. To all intents and purposes, IE11 is a dead browser.

**Comment by markconroy** [comment]
I ran a [survey on Slack](https://localgovdrupal.slack.com/archives/CSS2YS6BW/p1675766379629959) to see what usage was like for IE11 amongst councils. If below 2%, GDS does not actively support it.

- Essex: 0.002%
- Newcastle: 0.58%
- Copeland: 0.002%
- Argyll and Bute: 0.3%
- West Lindsey: 0.005%
- North Kesteven: 0.09%
- Blackburn with Darwen: 0.34%
- Bracknell Forest: 0.01%

From this survey, it looks like 0.58% is the highest user base of IE11, and that is more than 75% less than the govuk threshold for supporting something.

I propose we take the 🔥 flamethrower 🔥  to IE11.

**Comment by finnlewis** [comment]
Summary from Merge Monday discussion: 

 - GDS suggest not supporting if below 2% IE11 usage
 - If we drop IE11 support, we can free ourselves up to do more modern styling
 - we've not heard any reports of IE11 users.
 - There will be an update published tomorrow that will automatically update IE11 to Edge: https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11 

Quick check with those present: 

Maria: yeah, happy. Is it just the IE11 css to be removed? Yes. Other modern things? 
 - Mark: Using grid vs flex. Improves debugging.
Andy: major version of localgov_base, or at least upgrading the minor release number (not just a patch number).
 - Mark: probably a minor version bump. 
Ekes: maybe minor version
Stephen: let's drop it! Minor version might be easier for release. 
Finn: yeah! I might do some research to check what other projects have done with release version major/minor when dropping support for IE11

Next steps:

- Mark will create a pull request

**Comment by markconroy** [comment]
PR #372
