### ISSUE TITLE
Theme Re-factor: Call out Box Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#35]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-29 at 19 22 20](https://user-images.githubusercontent.com/2183332/123848213-5d6b9300-d90f-11eb-8a49-6408549a84ef.jpg)

**Comment by markconroy** [comment]
Is this component needed? If it's just to put an image beside some text, I think the two-column layout should be fine - text in one column and image in the other.

**Comment by willguv** [comment]
@tom-steel to check from Dave's original designs how this is supposed to look

**Comment by willguv** [comment]
@andybroomfield to share links to any live examples

**Comment by andybroomfield** [comment]
eg.
https://www.brighton-hove.gov.uk/climate-change/becoming-carbon-neutral-2030

<img width="753" alt="Screenshot 2021-06-29 at 1 49 23 pm" src="https://user-images.githubusercontent.com/1467480/123800119-dd2e3900-d8e0-11eb-910e-723336cd1b87.png">

**Comment by andybroomfield** [comment]
Original BHCC Design specification for campaigns
http://design.brighton-hove.gov.uk/markup/campaign.php

**Comment by markconroy** [comment]
PR #71

**Comment by msayoung** [comment]
Stunning. 
@danchamp anything to add?

**Comment by danchamp** [comment]
Nice @markconroy!

In my test here there was a problem with the padding applied to the `.call-out-box--has-image` (I also see this on your test page):

<img width="802" alt="Screenshot 2021-07-01 at 14 28 32" src="https://user-images.githubusercontent.com/261421/124132350-a25f0900-da78-11eb-9530-9e52a177399f.png">

I think the padding needs to be applied to `.call-out-box__content` to have the bg colour extend to the edges?

**Comment by markconroy** [comment]
Fixed now @danchamp

**Comment by danchamp** [comment]
Thanks @markconroy, tested and working locally.
