### ISSUE TITLE
In header.js primary toggle now only toggles primary nav

### ISSUE THREAD

**Issue by ctorgalson** [localgovdrupal/localgov_base#352]
This is a regression introduced in #332, #334. Mea culpa.

[Line 87 of `header.js`](https://github.com/localgovdrupal/localgov_base/blob/1.x/js/header.js#L87) is currently:

```js
navInfo.primary.region.classList.toggle(regionActiveClass);                                                                                       
```
To match [the original functionality](https://github.com/localgovdrupal/localgov_base/blob/1.2.28/js/header.js#L96-L100), it _should be_:

```js
navInfo.primary.region.classList.toggle(regionActiveClass);                                                                                       
navInfo.secondary.region.classList.toggle(regionActiveClass);
```
PR follows shortly.

**Comment by finnlewis** [comment]
Thanks @ctorgalson , what actually breaks and what does the PR fix?

Just wondering how urgent a release is.

**Comment by ctorgalson** [comment]
Sorry for that @finnlewis :(

In the code we cleaned-up, clicking or tapping `button.gd-header__toggle--primary` would toggle the state of _every_ `.lgd-header__nav`.

In other words, clicking that button would toggle the primary _and_ secondary nav open or closed. I haven't looked at tons of LGD sites, but I can see that e.g. https://www.lbbd.gov.uk/ relies on this behaviour.

The default way this works (and a way to check an individual site) is:

- site at a breakpoint < 768px
- primary nav has content
- secondary nav has content
- primary and secondary nav are hidden until the primary nav toggle is clicked
- when the primary nav toggle is clicked, _both_ navs become visible

The PR restores this behaviour.

**Comment by finnlewis** [comment]
Cool, thanks @ctorgalson - I will aim to test and release quickly to reduce the chances of anyone hitting this.
