### ISSUE TITLE
Updating existing installation to 1.3.0 WSOD: Base theme stable9 has not been installed

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#359]
This has happened twice to me now on different sites. Both use sub-themes of localgov_base, both were on 1.2.29. I guess the change of base theme to stable9 caused the issue.

To reproduce:

`composer update localgovdrupal/localgov_base`
`drush cr`

Reload sites, results in WSOD:

```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Theme\MissingThemeDependencyException: Base theme stable9 has not been installed. in 
Drupal\Core\Theme\ThemeInitialization->getActiveThemeByName() 
(line 115 of core/lib/Drupal/Core/Theme/ThemeInitialization.php). 
```

Can fix with:

`drush theme:enable stable9`

**Comment by markconroy** [comment]
This was fixed in https://github.com/localgovdrupal/localgov/pull/492

**Comment by finnlewis** [comment]
Thanks @danchamp ! 

I tried to highlight this in the release notes: https://github.com/localgovdrupal/localgov_base/releases/tag/1.3.0

And we have the corresponding release to the profile which has a hook to enable stable9: https://github.com/localgovdrupal/localgov/releases/tag/2.3.13

Can I just check, are you using the localgov_base theme on sites with or without the localgov profile and did you run drush updb or equivalent? 

Thanks for reporting anyway!

**Comment by danchamp** [comment]
@finnlewis I was being lazy and just updated localgov_base without any respect for release notes or other packages! I'd usually follow a more responsible process, so it's on me really. :-)
