### ISSUE TITLE
Theme Re-factor: Image with Caption Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#36]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-17 at 15 27 16](https://user-images.githubusercontent.com/2183332/122416346-91929b80-cf80-11eb-9b8d-86b6ba08f26f.jpg)

**Comment by markconroy** [comment]
See PR https://github.com/localgovdrupal/localgov_base/pull/48

**Comment by msayoung** [comment]
looks good
