### ISSUE TITLE
Subtheming creates links to Google Fonts

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#365]
In https://github.com/localgovdrupal/localgov_base/blob/1.x/scripts/subtheme-items/templates/layout/_html.html.twig#L17-L19 there are some references to Google Fonts. This means that when you subtheme localgov_base, you end up with a page that makes requests to Google Fonts, even if you don't use this font - unless you remove these lines from the file.

Given [rulings on GDPR and Google Fonts](https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/), could we perhaps remove these, either by bundling a font in or defaulting to a system font?

**Comment by markconroy** [comment]
Hmmmm ... this should not be happening. Let's get it fixed.

**Comment by markconroy** [comment]
PR created for this. Looks like waiting for someone to find a "Good first issue" didn't work out for us 😄
