### ISSUE TITLE
HTML5 form validation 

### ISSUE THREAD

**Issue by gavin-webstuff** [localgovdrupal/localgov_base#367]
HTML 5 validation tooltip is not displayed on forms on chrome 

**Steps to reproduce** 

- any form seems to demonstrate the bug so long as the upon validation there is a need to scroll to element triggered

![html5_no_validation_message](https://user-images.githubusercontent.com/1315627/217530948-a33acf15-0507-402c-b447-51ca7c66e9c8.jpg)
![html5_validation_message](https://user-images.githubusercontent.com/1315627/217530986-36336d85-a91f-42b0-87b5-6c679bd31c03.jpg)

**Comment by andybroomfield** [comment]
Although this is focused on user login, and we should still fix the issue anyway for these cases, we should move away from using HTML5 validation if we want to match GDS guidelines.
see https://design-system.service.gov.uk/patterns/validation/

**Comment by markconroy** [comment]
I've created a follow up issue for disabling HTML5 validation: https://github.com/localgovdrupal/localgov/issues/503

**Comment by markconroy** [comment]
I'm going to close this issue since we have the related issue now in the localgovdrupal/localgov repo.
