### ISSUE TITLE
Theme Re-factor: Pull-out Quote Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#37]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-17 at 15 44 45](https://user-images.githubusercontent.com/2183332/122419643-f8b14f80-cf82-11eb-928a-41d6588f036e.jpg)

**Comment by markconroy** [comment]
PR: https://github.com/localgovdrupal/localgov_base/pull/49

**Comment by msayoung** [comment]
@markconroy Is there a case for using the `<blockquote>` element here? 
Otherwise, looks nice.

**Comment by markconroy** [comment]
Hi @msayoung 

The `<blockquote>` element is used as the main wrapper element in this component.

**Comment by danchamp** [comment]
@markconroy Presentation looks good, the only issue I see is that the Author is rendered inside the `<blockquote>` element, which I think should only contain the quoted text.

I like [the way it's shown on the HTML spec site](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element), using `<figure>` as a container, with a `<blockquote>` child and the author / citation in a `<figcaption>`.

**Comment by markconroy** [comment]
Thanks @danchamp that's a great idea. Updated now.

**Comment by danchamp** [comment]
@markconroy Thanks, markup looks good.

The `<blockquote>` left margin looks like it needs a reset since the class `.pull-out-quote` is applied to its parent now, and most browsers have a fairly large default margin on the element:

<img width="482" alt="Screenshot 2021-06-22 at 07 26 22" src="https://user-images.githubusercontent.com/261421/122874681-2bfd3100-d32b-11eb-8e2e-504723c9518a.png">

**Comment by markconroy** [comment]
Thanks Dan. That CSS is updated now.

**Comment by danchamp** [comment]
Thanks @markconroy, looks great now.
