### ISSUE TITLE
Theme Re-factor: Key Facts Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#38]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

**Comment by willguv** [comment]
@tom-steel can you show Dave's original design work for this?

**Comment by markconroy** [comment]
We don't seem to have any design for this, and it currently matches what is in the localgov_theme theme, so markng as ready for review.

PR #75

**Comment by msayoung** [comment]
Nice, thanks.
