### ISSUE TITLE
Services menu is single-column since removal of IE11 support in 1.4.0

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#387]
secondary-menu.ie11.css set the column-count for any element with class `menu` within the secondary region:

https://github.com/localgovdrupal/localgov_base/blob/32261e5237ceb20012de41e1f4fd103efa1aace1/css/components/secondary-menu.ie11.css#L25

secondary-menu.css sets the column-count in a rule that targets a class that doesn't appear to exist in the LGD codebase:

https://github.com/localgovdrupal/localgov_base/blob/bd8b480f86587bc804bdafceb2faf91a91e75b61/css/components/secondary-menu.css#L30

Verify by setting an earlier version of localgov_base as default theme, and inspecting the service menu. column-count is being derived from the IE11 CSS file:

<img width="219" alt="Screenshot 2023-02-23 at 13 50 53" src="https://user-images.githubusercontent.com/261421/220927076-433c30c6-c8dd-4676-8298-9159a0fd89dd.png">

**Comment by markconroy** [comment]
Hi @danchamp 

I think this should be set via the variable in variables.css: https://github.com/localgovdrupal/localgov_base/blob/1.x/css/base/variables.css

It's called `--secondary-menu-column-count`. Perhaps that has been overridden in your theme?

**Comment by markconroy** [comment]
Actually, ignore me. Looks like the menu name may have changed somehow. Or we got the class name wrong originally.

I'll get a PR for this.

**Comment by danchamp** [comment]
@markconroy No worries, thanks. :-)
