### ISSUE TITLE
Theme Re-factor: Tabs Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#39]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-table

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

**Comment by markconroy** [comment]
PR https://github.com/localgovdrupal/localgov_base/pull/55

**Comment by danchamp** [comment]
@markconroy This functions as expected with mouse or keyboard.

The buttons for tabs are rendering with system fonts, which are on the small side (13.33px in FF, 11px in Safari for me), so we probably want an explicit font-family (and size?) declaration for `<button>`.

Slight rendering issue on Safari:

<img width="622" alt="Screenshot 2021-06-22 at 14 42 12" src="https://user-images.githubusercontent.com/261421/122935560-57524100-d368-11eb-8125-a3750f052ac3.png">

Adding these three rules to [.tabs--initialised .tabs__controls button](https://github.com/localgovdrupal/localgov_base/blob/d4c0e1afd5b22a6ef0146948d46564df7270c8e4/css/components/tabs.css#L23) looks to fix both the above issues:

```
  font-family: var(--font-primary);
  font-size: 1rem;
  margin: 0;
```

I've done a quick screen reader test and there are nav issues moving between tabs and tab panels, these are related to [the js](https://github.com/localgovdrupal/localgov_subsites/blob/2.x/modules/localgov_subsites_paragraphs/js/localgov-tabs.es6.js) and not any changes here. Assuming the js is remaining in subsites_paragraphs I'll raise an issue there.

**Comment by markconroy** [comment]
Thanks Dan. That's updated now.

Yes, the JS will be an issue for the subsites_paragraphs repo. Thanks again.

**Comment by msayoung** [comment]
Looks good to me.

I see it's what happens with the current theme, but I'm interested that the tabs don't appear at smaller screen sizes. 
Anyway, I'm happy. 
@danchamp I'll leave it assigned to you.

**Comment by markconroy** [comment]
The tabs not appearing on small screens is part of the current functionality. I didn't want to upset that - I'm guessing it's that we presume there will be instances where tabs may need to wrap to more than one line on small screens.

If we want to look at that, I'd suggest we might do it as a new issue, outside of the "feature parity" approach of this phase.

**Comment by danchamp** [comment]
@markconroy Happy for this to be closed with an issue raised for small-screen consideration in the future.
