### ISSUE TITLE
Newsroom teasers don't seem to show correct focus state

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#396]
Would expect this to show the same focus state as other links

![image](https://user-images.githubusercontent.com/19519457/222896803-a93f5458-c101-49ef-b03e-9583bb06f28b.png)

**Comment by markconroy** [comment]
@keelanfh I've created a PR to fix this. I've no idea why it's happening on the newsroom teaser links, but not on other links across the site.
