### ISSUE TITLE
Single webform checkbox element doesn't have styling applied

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#397]
In the example below, I have one checkbox and then a checkboxes element. Checkboxes have the styling applied, but not the single checkbox.

![image](https://user-images.githubusercontent.com/19519457/223708593-326151ba-d6f9-4ddd-837a-f4151f8cc0b7.png)

![image](https://user-images.githubusercontent.com/19519457/223708379-663fd828-08d5-4680-8bec-792508ae1726.png)

**Comment by markconroy** [comment]
Thanks @keelanfh 

I'll put this next on my hit list.
