### ISSUE TITLE
Theme Re-factor: Featured Teaser Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#40]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/featured-content-page-test 

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-17 at 16 42 07](https://user-images.githubusercontent.com/2183332/122429876-066ad300-cf8b-11eb-8a1b-a89b0da90a3a.jpg)

**Comment by markconroy** [comment]
PR https://github.com/localgovdrupal/localgov_base/pull/50

**Comment by msayoung** [comment]
Thumbs up from me.
