### ISSUE TITLE
Theme Re-factor: Document Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#41]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/test-pages-documents

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

**Comment by markconroy** [comment]
PR https://github.com/localgovdrupal/localgov_base/pull/54

**Comment by danchamp** [comment]
@markconroy The link text for non-HTML documents should include both the file type and the file size, so all users know what to expect before activating the link - see [Link Purpose](https://localgovdrupal.org/accessibility/tests.html#_4-links-buttons) in our accessibility standards.

Given that, I wonder if this is really tabular data and would be better presented as an unordered list instead?

The paragraph type also needs a way to name the document resources so filenames aren't used - I've [raised an issue for this on Subsites](https://github.com/localgovdrupal/localgov_subsites/issues/45).

**Comment by markconroy** [comment]
Thanks @danchamp 

Can you check this again now? I have file types added now.

**Comment by danchamp** [comment]
Sorry @markconroy, I forgot that this is handled in localgov_theme with a preprocess function that adds the file type and file size to all file links:

https://github.com/localgovdrupal/localgov_theme/blob/9aca9ab6a60738dfa6b549fb6741638f406da7fc/localgov_theme.theme#L194-L218

This is the desired output, with both the file type and the file size as part of the link text:

<img width="773" alt="Screenshot 2021-06-29 at 08 58 53" src="https://user-images.githubusercontent.com/261421/123759958-506f8500-d8b8-11eb-9ac0-f8ad289f1782.png">

**Comment by markconroy** [comment]
Thanks @danchamp 

This is ready for testing again

**Comment by danchamp** [comment]
Thanks @markconroy, this is good for me now.
