### ISSUE TITLE
Service status page: layout not contained

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#412]
On a service status page the status message is full-screen width. I think its meant to be contained. 

https://demo.localgovdrupal.org/births-deaths-marriages-and-citizenship/status

![image](https://user-images.githubusercontent.com/3852805/225920837-51837f4a-67f5-49fe-86f2-9af1ba6cecfc.png)

**Comment by markconroy** [comment]
Contained? I dunno, I kinda like the ugliness of it like this!!! 🤣
