### ISSUE TITLE
<noscript> can only have descendants in <head>

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#42]
The `<noscript>` element in the header template has a `<style>` child element:

https://github.com/localgovdrupal/localgov_base/blob/275cefbe4bfc461cc3369e2a7fa08302363bba6f/templates/layout/header.html.twig#L6-L19

This is invalid HTML - [noscript can only contain text when in the `<head>`](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element).

The `<noscript>` element could be moved to the `<head>` (which will need a `html.html.twig` template) or we could use a `no-js` or similar class on body and move the styling to the theme CSS files.

**Comment by markconroy** [comment]
Hi @danchamp 

Thanks for that. I'm not actually sure I agree with the point. I think it's okay to have style in the `noscript` tag. In any case, I've added a `no-js` class to the `html.html.twig` file and remove it via JS if JS loads. Then use that class to style items when JS does not load.

See here: https://github.com/localgovdrupal/localgov_base/pull/43

**Comment by danchamp** [comment]
@markconroy it is okay, so long as it's in the head. The issue is that we can't rely on user agents to parse the children of `<noscript>` in the body, since the HTML spec says to expect text only. Like a lot of invalid HTML most UAs will handle it without problem, but I don't like assuming that will always be the case.

This is a nice solution though, thanks.
