### ISSUE TITLE
Show titles of previous/next pages in guide navigation buttons/links

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#422]
At the moment, the previous/next button on guide pages doesn't show any information about where the guide pages go:

![image](https://user-images.githubusercontent.com/19519457/214875208-acb32178-daf4-40a0-95e4-f2f051b53fa5.png)

Particularly for longer pages, this might mean that a user doesn't know what to expect when they click the link, especially on mobile devices - see example of a longer page below - and we might be expecting them . @helencalderon reminded me that this is an example where we can follow the [Recognition over Recall usability heuristic](https://www.nngroup.com/articles/ten-usability-heuristics/#:~:text=%236%3A%20Recognition%20rather%20than%20recall).

@markconroy did [some work](https://github.com/essexcountycouncil/send-lgdrupal/blob/main/web/themes/custom/anrt_lgd/templates/block/guides-prev-next-block.html.twig) on this for send.essex.gov.uk, which brings this more in line with the existing essex.gov.uk and the way that GOV.UK does it. Mark, if this was something that others wanted in LGD, I don't know how long this would take to move across?

![image](https://user-images.githubusercontent.com/19519457/214875465-7328d683-e98c-4ea5-a093-9285c7c1f3f1.png)

Example of this interaction in context:

<img src="https://user-images.githubusercontent.com/19519457/214867998-ea204c28-be9c-4e58-8374-c1831124cf77.png" alt="" width="50"/>

**Comment by markconroy** [comment]
Thanks @keelanfh 

To move this from Essex SEND to localgov_base would take a matter of minutes.

The only issue I have with us doing this is that it will affect any site currently using localgov_base as its base theme, and that might be a (breaking) change they are not expecting (or might be a welcome one).

I think we'll need to discuss this a bit, but it's an idea I would support.

**Comment by keelanfh** [comment]
Thanks @markconroy.

Absolutely, it's a significant change - which makes it an interesting one to work out and relates to the https://github.com/localgovdrupal/localgov/issues/488 discussion.

I don't know if it would be feasible to have this selectable as an option in config - default for new installations, but not changed for existing installations.

**Comment by finnlewis** [comment]
Discussing today in the backlog group: plus one for a configurable option to display as is or including the title of hte next page.

**Comment by finnlewis** [comment]
Discussing how to make this optional. It would be disabled by default, and existing installs can turn it on.

Options: 
 - present this as a config options in the admin UI following the same pattern Stephen has implemented for login redirects
 - have this as a css variable and the theme takes care of the logic.
 - block configuration (thanks Andy) options - the next / previous is a block, so we could add config options to the block config.
 - theme settings page.

Stephen: the block config option sounds good. 

Tasks: 

- [ ] update guides prev/next block to add config option to enable the title of next/prev page
- [ ] update the template in localgov_guides to honor the config
- [ ] update the corresponding template in the localgov_base 
- [ ] maybe update CSS in localgov_base to look lovely

**Comment by alexburrows** [comment]
I agree with the block options as such, allowing the checkbox option to show the next page title will be good enough. I think we can just have a description on the field that gives a ** Warning ** as such e.g.

** Warning: By enabling this option the next page title will be shown below the Next or Previous option for the button, this will affect all guide pages. **

**Comment by alexburrows** [comment]
I can take this one on - free up @stephen-cox for other tickets

**Comment by willguv** [comment]
Hi @alexburrows how are you getting on with this please? Apologies if I've missed other issues rolling through. Cheers

**Comment by markconroy** [comment]
Hi @willguv 

going to be live once we make a new release of localgov_base - probably Monday!

https://github.com/localgovdrupal/localgov_base/pull/481
