### ISSUE TITLE
Incorrect display of list-item markers when links are inside <li>

### ISSUE THREAD

**Issue by nbrettell** [localgovdrupal/localgov_base#423]
Setting all anchor links to inline-block display has caused the display of markers (bullet points) to appear at the bottom of multi-line list items. This might not have been the intended purpose.

![Demo site - with visible marker positions](https://user-images.githubusercontent.com/2014068/229474467-d676b27b-5cae-4b66-b1cf-fb008a13f0f7.png)

This was caused by the following commit: [changes to css \<a\> display](https://github.com/localgovdrupal/localgov_base/commit/ae8e922d91c1f8650d5813909e37429d86f9c025)

**Comment by markconroy** [comment]
Related issue: https://github.com/localgovdrupal/localgov_base/issues/426

**Comment by markconroy** [comment]
It might be worth reverting https://github.com/localgovdrupal/localgov_base/pull/408 (part of that was because of logo not displaying properly in some cases on Chrome), but there's another PR that (I think) fixed that, so maybe best to revert setting all links to `inline-block` by default.

**Comment by markconroy** [comment]
@keelanfh wanna test https://github.com/localgovdrupal/localgov_base/pull/429
