### ISSUE TITLE
Links not appearing alongside other text since <a> set to inline-block

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#426]
Longer links are appearing on separate lines from the surrounding text since the change to all links being set as `inline-block` (https://github.com/localgovdrupal/localgov_base/commit/ae8e922d91c1f8650d5813909e37429d86f9c025). This looks quite unsightly and I think should be changed back to the previous behaviour.

Before :

![image](https://user-images.githubusercontent.com/19519457/233371422-a65ed758-144e-4954-a590-1dfe6d725095.png)

After:

![image](https://user-images.githubusercontent.com/19519457/233371535-f16747a8-2707-4893-b8be-673da7c62eb8.png)

**Comment by willguv** [comment]
Was there a reason for this change @markconroy? Thanks

**Comment by markconroy** [comment]
There's an issue for this already: https://github.com/localgovdrupal/localgov_base/pull/424

**Comment by markconroy** [comment]
@keelanfh let's continue the conversation at #423
