### ISSUE TITLE
On creating a new blog channel, the posts are aligned to the left rather than in the middle

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#456]
Not sure if one for localgovdrupal/localgov_blogs, there might be some special configuration steps that need to be completed - but I'd expect the blog posts to be in the main content area rather than off to the left.

![MicrosoftTeams-image (1)](https://github.com/localgovdrupal/localgov_base/assets/19519457/c7244dad-d979-467c-8dd6-7c5c12945aeb)

**Comment by markconroy** [comment]
PR created at #470
