### ISSUE TITLE
Theme Re-factor: Fact Box Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#46]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/example-page-different-page-components

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-17 at 13 14 49](https://user-images.githubusercontent.com/2183332/122394756-39eb3480-cf6e-11eb-889c-278b03b09ff5.jpg)

**Comment by markconroy** [comment]
Ready for review. See PR https://github.com/localgovdrupal/localgov_base/pull/47

**Comment by markconroy** [comment]
Video here: https://www.youtube.com/watch?v=TahBN93lugU

**Comment by msayoung** [comment]
looks good
