### ISSUE TITLE
Highlight unpublished Guide pages

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov_base#465]
At the moment, unpublished Guide pages appear within the Guide content table when the viewer has editing rights to the Guide. This is not good UX as what the editor sees is not what a nonlogged in user sees. For better UX, such unpublished Guide pages should be clearly highlighted. We have similar highlighting for unpublished Service pages listed within Service (sub)landing pages.

[Example Guide](https://lbc-app-w-localgov-corpwebsite-p.azurewebsites.net/housing/home-owners-and-leaseholders/staying-put-service) where the Staying put Guide page is listed but unpublished.

This feature should become part of the localgov_guides module.

**Comment by markconroy** [comment]
I think we should fix this at the localgov_base level, so moving this issue to there.

**Comment by markconroy** [comment]
PR in #476 should fix this.

**Comment by markconroy** [comment]
I'm closing this, as we will fix it at a wider scale across LGD instead of just guides.
