### ISSUE TITLE
Accessibility - Headings are in sections & sub-sections

### ISSUE THREAD

**Issue by Revanuru** [localgovdrupal/localgov_base#473]
Actions: Checking the compliance with WCAG 1.3.1 https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html:
The expected result: Screen Reader - Headings are in sections & sub-sections
The actual result was : Heading levels have been skipped on the following Essex intranet pages. 
1. https://preprod.essex-intranet.nomensa.xyz/taking-time-off
2. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/annual-leave
3. https://preprod.essex-intranet.nomensa.xyz/family-leave
4. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/leave-personal-development
5. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/loss-and-bereavement-leave
6. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/medical-and-heathcare-appointments
7. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/unplanned-leave
8. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/loss-and-bereavement-leave/parental-bereavement-leave
9. https://preprod.essex-intranet.nomensa.xyz/taking-time-off/medical-and-heathcare-appointments/physiotherapy-and-rehabilitation-appointments
Observation: The titles are set up to be h3's instead of h2's, h2 title  is being skipped, hence screen reader is picking h3 straight after h1. This needs to be fixed. 

What needs to be done: LGD's approach on service landing pages was to introduce a visually-hidden h2 in between the h1 and the h3 so would expect LGD to favour a similar approach for these service sub-landing pages.

**Comment by markconroy** [comment]
Hi @Revanuru 

The component that is creating those sub-sections is called a "Topic List Builder". It has a field on it to put a title before those items. That title will be in a `<h2>` if filled in.

You can see it on the demo site here: https://demo.localgovdrupal.org/adult-health-and-social-care/another-service-landing-page

![Screenshot 2023-07-21 at 13 27 16](https://github.com/localgovdrupal/localgov_base/assets/2183332/dbe86ca4-1057-4daf-9bda-a37c76cbc6d4)
