### ISSUE TITLE
Pink background on unpublished pages viewed through preview links

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_base#487]
#464 has brought back pink backgrounds to unpublished pages.  Problem is, when such pages are shared using preview links from the "Preview Link" tab of a page, the pink background is causing confusion among recipients.  People are wondering if the pink background is going to stick when the page is published later.  Sample screenshot from an unpublished Guide page shared through a preview link:
![screenshot-preview-link-page-pink-bg](https://github.com/localgovdrupal/localgov_base/assets/50206849/97a3dd2a-a0bb-4c9f-9ec4-fa9b1f446991)

Copying @DavidBAsch @finnlewis @markconroy @msayoung

**Comment by willguv** [comment]
@Adnan-cds thanks for flagging. Are you going to propose a fix for this? 

I wonder (copying @stephen-cox) if this is related to the [preview link issue](https://github.com/localgovdrupal/localgov/issues/600) where content designers have to share multiple links to with service contacts to get content checked.

If we were to have a "Service contact" read only user, we could remove the pink background for them.

What do you both think?

**Comment by DavidBAsch** [comment]
@willguv To be honest I don't like it at all. I find it difficult to visualise the content when editing, as well as sending to the service when it's displayed like this.

**Comment by Adnan-cds** [comment]
> Are you going to propose a fix for this?

Sorry, nothing in mind.  Mark @markconroy asked me to raise this ticket in Slack.  I thought Mark wants to fix it.  If Mark is unavailable then we can try asking Chris @cjstevens78.

> I wonder if this is related to the https://github.com/localgovdrupal/localgov/issues/600 where content designers have to share multiple links to with service contacts to get content checked.

Not entirely related although this issue is going to affect **any** previewed page that is still not published.

**Comment by willguv** [comment]
Thanks @DavidBAsch I must admit this one went through without a lot of discussion. I assumed that it would be something everyone would want - sorry, lesson learned!

I think the next thing we should do is toggle this effect on/ off on a whole site. What do you think? Copying @markconroy as he might be able to do the work

Thanks all

**Comment by DavidBAsch** [comment]
@willguv It might just be me that doesn't like it, though 🤔

**Comment by andybroomfield** [comment]
Just to add, this is how we do it at Brighton. I think it's important that we have some indication that a page is unpublished. We could look at donoring this after the Drupal 10 work as it's quite straight forword.

<img width="1204" alt="Screenshot 2023-10-10 at 12 29 11 pm" src="https://github.com/localgovdrupal/localgov_base/assets/1467480/97dc0526-0e7c-4e86-8c5d-e764c5dcbe79">

**Comment by DavidBAsch** [comment]
If the purpose is to make people aware it's still in draft then perhaps something like:

# Your service page [DRAFT]

Content
.......

Would be better than this:

![image](https://github.com/localgovdrupal/localgov_base/assets/14923610/3b51b50c-b3ba-4980-97dc-819a13e74f9b)

**Comment by markconroy** [comment]
I really like @andybroomfield's approach. A banner across the top saying "This page is not published ..."

**Comment by stephen-cox** [comment]
+1 for a banner making it clear the page is unpublished.

**Comment by DavidBAsch** [comment]
The problem I see (or don't see) with banners is they could easily be obscured by live site banners.

![image](https://github.com/localgovdrupal/localgov_base/assets/14923610/8bbfd98a-17a8-48a4-aeb8-15e13b70746b)

**Comment by andybroomfield** [comment]
Make it in page like a system message?

**Comment by markconroy** [comment]
We have a new approach to this now based on #495 

If anyone wants to create the message banner proposed in this issue as an extra bonus feature, that would be cool.

**Comment by willguv** [comment]
Maybe the banner is at the very top of the page? It could be an option, same as pink background and appending the word [DRAFT]

Thanks in advance for donating if you do it @andybroomfield - much obliged!

**Comment by markconroy** [comment]
Any thoughts on how the banner approach might work when the unpublished page is an entity reference/teaser inside another page (which may or may not also be unpublished)?

**Comment by Adnan-cds** [comment]
If it helps, on Service landing pages and Service sublanding pages, we mark unpublished child pages as "Unpublished".  Screenshot follows:
![image](https://github.com/localgovdrupal/localgov_base/assets/50206849/d90438c3-d017-4fd6-aaa5-3e70437a5b46)

**Comment by markconroy** [comment]
We've had this open a year with no movement.

I've read through the issue and thought it was about the pink on unpublished, but that seems fine now and this issue has developed into talking about a banner on the top of the page.

Since there's no movement on this, I'm going to close this issue. We can open a fresh one later dealing specifically with the idea of placing a banner at the top of the page if any gains the appetite for it.
