### ISSUE TITLE
Update Github workflow to test Drupal 10

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#489]
@Adnan-cds mentioned an error when testing with Drupal 10 from a custom theme.

Might be good to update the Github workflow to test against Drupal 10 too. 

And PHP 8.2? 

https://github.com/localgovdrupal/localgov_base/blob/1.x/.github/workflows/test.yml#L26

@markconroy @stephen-cox thoughts?

**Comment by rupertj** [comment]
I did this recently when I added the test coverage for #497. It's already merged (https://github.com/localgovdrupal/localgov_base/pull/512/files), so I'll close this ticket.
