### ISSUE TITLE
Click anywhere on the page to close the Services menu

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#494]
Requested by David Upjohn, Oxfordshire

> Is there a way to get the All services/mega menu to contract if a user clicks on another part of the page (not the up arrow)? In user testing people are clicking the services menu but want to close it and get rid of it.

![Image](https://github.com/localgovdrupal/localgov_base/assets/708140/6ff674b5-b3be-4498-b4df-2a3c9ce08b47)

**Comment by markconroy** [comment]
Closing this in favour of #517
