### ISSUE TITLE
Display options for unpublished pages

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#495]
Following on from pink backgrounds in https://github.com/localgovdrupal/localgov_base/pull/476, which haven't been universally popular

We need to provide options which could be:

- turn off pink background for everyone/ specific roles
- don't show pink background on pages accessed by Preview Link
- show the word "Draft" instead of pink background

**Comment by JimmyGreenatron** [comment]
I'd vote for show the word "Draft" instead of pink background, as this meets the need to clearly see what's in draft, while also showing what the content will look like when published

**Comment by carolinemccabe** [comment]
I'd agree with @JimmyGreenatron on this one!  The most important factor for me being is that when we share stuff in draft with stakeholders, it should look as close to the real thing as possible.

**Comment by willguv** [comment]
From @markconroy 

I think we should be able to have 2 theme settings
Add pink background to unpublished pages (checkbox on/off)
Add “Draft” to title of unpublished pages (checkbox on/off)

**Comment by markconroy** [comment]
Here's a short video of that the PR in #500 does

https://youtu.be/yJr1NB8nwlo

**Comment by carolinemccabe** [comment]
Much better, thank you!

**Comment by willguv** [comment]
Thanks @markconroy this is great

Could we put the word "Draft" at the end of the title and format like this "[Draft]"
