### ISSUE TITLE
Change text to mailto

### ISSUE THREAD

**Issue by bisd** [localgovdrupal/localgov_base#496]
The enquiries email address on this page is text rather than a link - I am assuming it should be a mailto?

https://demo.localgovdrupal.org/national-parks-uk/loch-lomond-and-trossachs

I wasn't able to establish which repo this issue belongs to - maybe someone could help? Thank you.

@msayoung

**Comment by markconroy** [comment]
Hi @bisd 

There is currently no template for that item. It was set up originally as a text field instead of an email field for some reason.

If you want to turn it into an email field, you could duplicate the `field.html.twig` file and call it `field--node--localgov-directory-email--localgov-directories-venue.html.twig` then edit that file to make it an email link.

Note however, that that _might_ break existing sites if they have already set an email link for this field in the node template or somewhere else (this is only a _might_, we'd have to test to see).

**Comment by bisd** [comment]
Thanks @markconroy 

I just wanted to check to make sure that this is a text field since the field seems to be defined in the content type as an Email field unless I am nistaken (and if so my sincere apologies).

Could you also please be kind enough to point me in the direction of some template files which do this sort of thing (or some resources which show me how to edit twig templates in this way) so that I can take a look? Many thanks :-)

![enquiries_email](https://github.com/localgovdrupal/localgov_base/assets/2633608/dd6084fa-dcec-4af3-9d8c-8736487dda72)

**Comment by bisd** [comment]
Thanks @markconroy. Sorry but I am not sure what you meant by it not being an email field since it seems to be an email field (please see attachment below). I have created a twig template with the suggested naming convention. I am not sure what the best way is of testing it is before it is merged but I have submitted it as a pull request anyway. Please let me know if there is anything I can do to help with the testing.

![enquiries_email](https://github.com/localgovdrupal/localgov_base/assets/2633608/400f41cd-82af-4c4e-80c3-5a2f22667d47)

**Comment by ekes** [comment]
As it's a email field the formatter could be changed.

![image](https://github.com/localgovdrupal/localgov_base/assets/237186/e79bdd89-f36f-48e8-88e1-2f5cf7b05ef5)

![image](https://github.com/localgovdrupal/localgov_base/assets/237186/fc70036d-fd0c-4f22-b737-837f6a1d6ba5)

**Comment by ekes** [comment]
So it's the default set in LocalGov Directories in this line

https://github.com/localgovdrupal/localgov_directories/blob/f871834f2e2a60e10d5b2a2ba6a49db889a7d7c6/modules/localgov_directories_venue/config/install/core.entity_view_display.node.localgov_directories_venue.default.yml#L74

Exporting config after changing the setting from plain text to email and looking at the exported config you can see what the line should become to set it to email by default. That way is maybe easiest to make a PR against `localgov_directories` to change the default.

**Comment by bisd** [comment]
I have made a new pull request against localgov_directories to change the field formatter default [here](https://github.com/localgovdrupal/localgov_directories/pull/341).

**Comment by markconroy** [comment]
Sorry, my mistake. I thought it was a text field we had here since it's format was 'plain text'.

**Comment by markconroy** [comment]
Looks like the associated merge request for this has been merged, so I'll close this issue.
