### ISSUE TITLE
In a new theme, where should templates live?

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#5]
Let's open this issue to agree where templates and styling should live for our components.

When providing an option/suggestion, please think through benefits _and_ drawbacks to that approach.

**Comment by markconroy** [comment]
One suggestion: move them all the the theme.

If we move them to the theme
- It's easier for us (and anyone else) to know exactly where to go to find each template
- The library for each component will have a predictable naming convention `{{ localgov_base/accordion }}`
- We can create a theme setting "Include localgov_base CSS" and "Include localgov_base JS" which can be turned on by default and then if any individual site wants to use just our templates but their own CSS and/or JS, unchecking those is easier than overriding loads of module libraries via libraries_override in the theme.info.yml file
- If someone wants to use a module outside of localgov Drupal, they simply need to grab that module's templates from them theme (which can all be inside a specific directory in the theme) 
- - /templates/components/accordion/accordion-template-1.html.twig, 
- - /templates/components/accordion/accordion-template-2.html.twig,
- - etc
- We won't have CSS classes dropped into templates in modules that then appear like that module has a dependency on a specific theme or library (such as we currently do with classes like .row and .wrapper)
- Editing the frontend in the future will mean editing mostly one repo; currently we need to edit lots of repos to make large changes to the frontend (such as this current theme)
- Drupal currently provides are few templates as it can in modules, such as paragraph.html.twig - that just renders {{ content }} same as node.html.twig just renders {{ content }}
- It means our modules are not forcing specific CSS on other websites - such as colours, fonts, widths, etc.
- There is less chance of us creating dependent templates (such as node--news--teaser.html.twig and node--event--teaser.html.twig), and great chance of us using reusable templates (such as node--teaser.html.twig)
- CSS is maintained in one place, so should be easier to keep track of

I'll add more as I think of them (been a long day of thinking so far!)

**Comment by markconroy** [comment]
Another suggestion: keep them all in the respective modules.

If we do this:
- The modules can work without dependencies
- Modules are styled out of the box

I can't think of much more off the top of my head at the moment.

**Comment by andybroomfield** [comment]
This leads me to re-ask a question which is how supported is installing the modules stand alone vs the distribution going to be. BHCC considers it esential to be able to use the modules without doing a full site rebuild.

Thats not to say templates can't move, and be used as an example. But it does make mainatainability a little difficult with updates. Could the modules still provide the equivilent of stable templates. These don't have to be complex, I think we have already aggreed to remove node type templates and replace them with generic ones in theme based on display modes so really content types such as service_landing_page et all need to have a more sensible manage display configuration set up and then councils maintain their own template for pages like this, using the template in base as a start.

I think its safe to assume that those who install the modules stand alone know what they are doing, however it should still be documented so there are no surprises about why things look a little strange without the right templates.

Step by Step, Subsites and Guides I think those pages are quite dependant on the bundled templates which get used in various blocks so those are going to not work right without there bundled templates. 

I'm going to suggest Alert Banner maintains its template as a custom entity it needs to have a template in there.

Not sure about some other templates such as the page header block, its kind of a custom thing so does need a template.

**Comment by willguv** [comment]
Thanks for making this point @andybroomfield. I sometimes forget that Brighton & Hove is our best example of a council using some modules and not others. We need to take this into account and not put any barriers in place for you (and others)

**Comment by markconroy** [comment]
Perhaps, then, for this project, we only move reusable templates to the new them, with sensible defaults?

This means: 
- node.html.twig
- node--teaser.html.twig
- region.html.twig
- page.html.twig
- Etc

And we leave templates that are specific to modules in their modules.
- Step by step
- Alert banner
- Accordion
- other paragraph types, etc

Some of these templates in modules might then have classes (as they currently do) that presume a dependence on classes within the them, such as 

```
<div class="localgov-row">
  <article class="localgov-row__two-thirds">
   {{ content }}
  </article>
  <aside class="localgov-row__one-third">
    {{ sidebar_items }}
  </aside>
</div>
```

Perhaps this grid system (it's based on the GDS layout system and can be completed in about 30 lines of CSS) could become a module, so any site can use it outside of our theme? And then the theme will have those classes available as well.

**Comment by andybroomfield** [comment]
@markconroy That could work, it might be complicating it a little bit. I think the inbuilt module template if they exist should use generic names and maybe not assume anything about which grid is in use, like the work you have done with the Alert Banner. 

Would it be too much duplication for the theme to then include versions of the templates with the localgov grid layout?

Thinking that in future (not imediate priority) we are going to need template versions in various grid systems, GDS, Bootstrap, Tailwinds etc. I know Croydon is Bootstrap heavy, whilst BHCC is moving away from defined frameworks for layout. Like a module or base theme that has the template with the appropriate classes in place.

Agree in moving generic templates, and anything that is really node based. Its more templates that are theming a block or a view display like step by step does.

Paragraphs is more complicated as they are expected to do something, things like text / image 50 / 50 don't really work on thier own unless they have bundled template and css.

**Comment by willguv** [comment]
@markconroy @andybroomfield I know that Croydon and Design Dave really like Bootstrap, so would want to properly understand a move away from that would mean for LGD and for them. I'll try to get a chat in the diary soon.

**Comment by markconroy** [comment]
Thanks @willguv that could be a good chat to have.

Rather than wondering why we would move away from bootstrap, I'd like to understand what bootstrap brings to the project. Especially what it brings to the project that we can't create and easily maintain ourselves. I often see bootstrap used mostly for creating layouts, but as I mentioned above, we can have a very nice layout system in 30 lines of CSS rather than the huge overhead of bootstrap.

I'd much prefer our base not to have a reliance on any framework, and then let others use tailwind or bootstrap or whatever they wish as an extension, but it would mean that not all councils in the future have bootstrap forced on them, especially councils like BHCC that are actively trying to move away from frameworks.

**Comment by willguv** [comment]
Am showing my ignorance of such things @markconroy. Agree that your chat would be a very good one to have. Would you be up for a short technical chat with product people who don’t really follow what Bootstrap, Tailwind etc are?

**Comment by markconroy** [comment]
Yep, any time at all suits me.

**Comment by markconroy** [comment]
I've created a Twitch with a demo of what I would like to use for our grid/layout system. It's 30 lines of CSS.

The Twitch is here - https://www.twitch.tv/videos/1004800800

I'll upload it to YouTube when it's finished processing on my computer.

**Comment by markconroy** [comment]
I'm going to close this issue as the theme is now live and there doesn't seem to be conflict about the templates being in it.
