### ISSUE TITLE
Bullit points visible with pager items on multiple pages in Windows High Contrast Mode

### ISSUE THREAD

**Issue by bisd** [localgovdrupal/localgov_base#501]
The bullit points next to page numbers are visible when Windows High Contrast Mode is turned on. A css quick fix may be to set `[list-style-type]: none;` on the unordered list for the pager items.

An example may be seen on this page:
https://test.localgovdrupal.org/events

This is what it looks like on WHCM:
![pager_items](https://github.com/localgovdrupal/localgov_base/assets/2633608/12015d2e-fd0b-4820-9991-e8fd4801e698)

@msayoung

**Comment by markconroy** [comment]
Hi @bisd 

I don't have a windows computer to test/fix this. Would you be able to create a PR for it?

**Comment by bisd** [comment]
Sure Mark I will have a go this afternoon.
    On Friday, 17 November 2023 at 10:54:02 GMT, Mark Conroy ***@***.***> wrote:  
 
 


Hi @bisd

I don't have a windows computer to test/fix this. Would you be able to create a PR for it?
