### ISSUE TITLE
Limit line length to something sensible

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#51]
On pages such as http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship/registering-birth the line length is pretty long. The recommendation is between 50 -120 characters per line. https://webaim.org/techniques/textlayout

Can we limit the main content section to 2/3rd of the full width at larger screen sizes? 

Discuss!

**Comment by markconroy** [comment]
See PR https://github.com/localgovdrupal/localgov_base/pull/52

**Comment by danchamp** [comment]
@markconroy @msayoung This looks good to me.

**Comment by msayoung** [comment]
Looks good, and I see we can add other content types to the list of restricted widths in templates/content/node--full.html.twig
thanks @markconroy
