### ISSUE TITLE
Services header drop down menu not closing

### ISSUE THREAD

**Issue by davidupjohn** [localgovdrupal/localgov_base#517]
As a user I want the services menu (in header) to disappear/contract if I click anywhere that isn't a link in the services drop down menu in the header.

If you click anywhere on the page that isn't in the menu then then menu should go away.

**Comment by markconroy** [comment]
Moving to `localgov_base` for consideration

**Comment by markconroy** [comment]
Hi @davidupjohn 

Can you give #522 a test if you are able to please?

**Comment by davidupjohn** [comment]
@markconroy I only have access to gitpod and I'm not a developer so is there some way I can test it in that ? If not I'm sure its all working beautifully.

**Comment by markconroy** [comment]
It's definitely working, but I want to make sure we get someone to check that the code is fine (I believe it is) and it doens't introduce any accessibility issues (I believe it doesn't). 

I've tagged Finn and Maria and Christopher as well on the PR so hopefully one of them can check on it and we'll get a new release straight after that.

**Comment by finnlewis** [comment]
Testing now!
