### ISSUE TITLE
Move the template for the localgov_numbered_text paragraph from publications to localgov_base.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_base#520]
We've already moved the localgov_numbered_text paragraph from the publications module to localgov_paragraphs, but there's a custom template for it left in the publications module. As all the other paragraphs supplied by localgov_paragraphs have their templates in the base theme, the one for numbered text should be here too.

**Comment by andybroomfield** [comment]
Should go in localgov_paragraphs with the paragraph type, as not all themes will use localgov_base. Then a copy can be added to localgov_base for customisation there. I think this is the same pattern used for other paragraph types and also allows it to show in the paragraphs preview / layout builder when in the admin theme.

**Comment by rupertj** [comment]
I don't think it does work like that. I can't see any theming for the paragraphs defined in localgov_paragraphs in that module, but there are some in localgov_base.

And while you're right that not all themes will use localgov_base, I'm thinking that if you've chosen not to use it, you probably don't want default theming.

**Comment by andybroomfield** [comment]
Hmm, ok, looks like its only the [paragraph subites module](https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_subsites_paragraphs/templates) that contains the templates.

Generally it is good practice to include a basic template with the module with the base theme then having the specific markup it needs. As its a paragraph it should get the general template so maybe it's fine for numbered paragraph?

**Comment by rupertj** [comment]
So it turns out this whole issue was redundant (sorry!). Having looked at the template that needed moving, it just replaces the core wrappers with some different ones, and there isn't any CSS that applies to the other wrappers, so I'm just going to remove it from localgov_paragraphs instead.
