### ISSUE TITLE
Add new region for subsites extras module menu

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#526]
Tasks

- [x] Add region in localgov_base.info.yml
- [x] Add region to header.html.twig (probably just inside closing header tag so it can be optionally full width)
- [x] Add toggle button for expanding/collapsing menu on small screens
- [x] Add JS to header.js to support the toggling
- [x] Provide some basic default styles via custom variables for menus in this region

**Comment by rupertj** [comment]
I've started a branch for this. There's a daft PR here: #542
