### ISSUE TITLE
Add External Link Icon for external links.

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#53]

**Comment by keelanfh** [comment]
On this - I noticed that there are a couple of styles for external links and PDF links in LocalGov Drupal. We've actually removed these, following the [GOV.UK Design System approach](https://design-system.service.gov.uk/styles/typography/#external-links), which in turn links to some (albeit quite old) [research](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/).

One of the subtle aspects of this is that we don't want to 'warn' or cause friction to users when we're directing them to another part of government that they need to interact with to complete a task.

Anyway, just to feed back that we removed these styles from our install and won't use them.

**Comment by markconroy** [comment]
Based on the info in that blog post, let's close this.
