### ISSUE TITLE
'Add to calendar' for Events

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#532]
Almost done - try it at

http://essex-1.mc.anner.ie/events/single-event
http://essex-1.mc.anner.ie/events/test-repeating-event

**Comment by willguv** [comment]
@markconroy have you done a PR to LGD for this? Thanks!

**Comment by markconroy** [comment]
The work I have done for this is specific to Essex Co Co. I'll have to get a bit of spare time to make it just a little more generic and/or configurable for LocalGov in general.

Shouldn't take very long (maybe 2 hours or so).

**Comment by markconroy** [comment]
Moving to localgov_base

**Comment by willguv** [comment]
Cheers Mark, great work!

**Comment by willguv** [comment]
@markconroy have you pushed this back to LGD? Am thinking not. Thanks

**Comment by markconroy** [comment]
Not yet. I want to get it deployed for Essex first and then think about how to make it a little bit more generic for LGD.

**Comment by willguv** [comment]
@markconroy this would also be good to finish off

**Comment by markconroy** [comment]
PR added for this, here: https://github.com/localgovdrupal/localgov_base/pull/546

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by msayoung** [comment]
This is great @markconroy 

Is there a danger in enabling this by default? Should we be giving people the option to switch this on sitewide, or on an event by event basis ?

**Comment by willguv** [comment]
What might the danger be @msayoung? Keen to have a bit more thinking about when to enable by default and not so would be good to chat about it. Cheers

**Comment by msayoung** [comment]
Not sure to be honest, but this change will mean this Add to Cal function will appear on every event on everyone's site as soon as they update the base theme (unless they have already overidden that twig template). 

I don't think that's necessarily a bad thing, just thought I should ask the question.

**Comment by finnlewis** [comment]
Discussing this in Merge Tuesday: 

Enabling by default on existing sites, for sites that have not overridden this template, will automatically add the button to 'Add to calendar' to event node full view.

We're happy with this (@willguv, @markconroy,  @ekes, @stephen-cox, @FinnERLewis )

@andybroomfield would we consider moving this to the events module, to a pseudo field?
