### ISSUE TITLE
Use prev-next.twig for publications prev-next

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#564]

**Comment by ctorgalson** [comment]
@markconroy Questions about this one: is the intention for `localgov_base` to change the _look_ of the Publications prev/next nav along with the markup (see screenshot)?

![image](https://github.com/user-attachments/assets/8e38589c-f119-4328-9072-bc763ea254eb)
 (Left: current, right: using `localgov_base`'s `prev-next.twig`)
 
 If the look and feel are to stay as-is, do we want to address it in CSS, or should we add condition in `prev-next.twig` that leaves out the default classes if, say, a variable like `omit_template_classes` is defined?

**Comment by markconroy** [comment]
The intention is to have all Prev/Next components looking identical, so if any council changes their design for prev/next they will only need to update the CSS in one place.

**Comment by ctorgalson** [comment]
@markconroy I didn't actually push up any code for this yet :)

Does the design uniformity extend to the positioning? On Publications, the Prev/Next buttons are in the main content area, but there's a sidebar, so they're not at the far left of the layout.

**Comment by markconroy** [comment]
Sorry, I don't even remember clicking the close button. 

Yes, I think it should also extend to the positioning. If that's more difficult, maybe a follow-up issue will be good enough and we just focus on the style/template in this issue.

**Comment by ctorgalson** [comment]
@markconroy created #596. 

It looks ok, but moving the nav to a full-width region probably means creating a block for the nav as is done for other components (the current nav is part of the node content, so can't really move out of the region including the sidebar).

**Comment by ctorgalson** [comment]
Closed by #596
