### ISSUE TITLE
Services menu button: focus order and announcements

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#578]
Initial issue reported by @waako 

Using a keyboard to navigate tab through the header and press enter to expand the Services menu. Tab through the menu items. Note that you skip the other header items. 
Problem: a non-sighted keyboard user may miss these header items. 
The expected behaviour would be that you leave the menu items and return to the other header items. 

Issue 2. : Auto closing of the Services button
Tested on NVDA screenreader / Firefox

- When you land on the Services menu in the collapsed state "Services, expand and jump to services menu, collapsed" is announced. 
- Press ENTER
- You are moved to the Services menu
- Press SHIFT and TAB to go back
- You are returned to the Services button and "Services, expand and jump to services menu, expanded" is announced , however the button automatically collapses. 
- Without moving, announce the current item:  "Button collapsed, Services: expand and jump to services menu"  

Problem: The button automatically collapsing does not align with the state announced by the screenreader. 
Recommendation: I don't think we need to automatically close the button when you return to it. The user can decide whether to close it. 

Issue 3: Aria label
I think the aria-label is too verbose. We could shorten it to "Services: jump to services" and leave the expand / collapse announcement to the aria-expanded. 

----
Note: to discuss and create another issue if needed. 
I know why the services menu works like it does, but I'd be interested in exploring a redesign from scratch so that we can use a natural focus order and not need to "jump" to the menu. 
I would imagine we'd need to offer an alternative header option, so that we don't break the existing sites.

**Comment by markconroy** [comment]
Thanks for the report of this issue. It's a nice juicy one to get working on. 

Sorry, but that's all the input I have for now on this :smile:

Maybe next week or the week after I could try set aside a full day to figure the 3 issues out. And after that, we can think of a way to do the "new header" which I'd love to do. And I think that would give us less headache if we try to use localgov_base as the base theme for other projects, such as NHS.

**Comment by msayoung** [comment]
This looks amazing @markconroy !
