### ISSUE TITLE
Empty `<p>` tags in quick facts section

### ISSUE THREAD

**Issue by sgroi-l** [localgovdrupal/localgov_base#608]
### Description

The "Quick Fact" section on the service page contains empty `<p>` tags. These empty tags do not contribute to the content and should be removed to clean up the markup.

### Expected Behaviour

- HTML markup should be clean and free of unnecessary empty tags.
- Empty `<p>` tags should be removed to improve readability and maintainability of the code.

### Actual Behaviour

- The "Quick Fact" section includes empty `<p>` tags that do not contain any text or content.

### How to Replicate

1. Visit the service page, such as [this example page](https://a11y.localgovdrupal.org/adult-health-and-social-care/another-service-landing-page/service-page).
2. Inspect the HTML markup of the "Quick Fact" section.
3. Locate and verify the presence of empty `<p>` tags within the section.

### Code Snippet

```html
<div class="field field--name-label field--type-string field--label-hidden field__item">quick fact</div>
<div class="field field--name-paragraphs field--type-entity-reference-revisions field--label-hidden field__item">
  <p class="fact-box__opening">Quick Fact example</p>
  <div class="fact-box__fact">
    <p></p> <!-- Empty <p> tag -->
    <div class="field field--name-localgov-fact field--type-string field--label-hidden field__item">9 out of 10 councils prefer LocalGov Drupal!</div>
    <p></p> <!-- Empty <p> tag -->
  </div>
  <p class="fact-box__closing"> Source: the internet</p>
</div>

**Comment by markconroy** [comment]
I think this is fixed via https://github.com/localgovdrupal/localgov_base/pull/617

Closing. Please re-open if issue persists.
