### ISSUE TITLE
Focus appearance on video play button

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#610]
The focus ring on the video play button is pretty hard to see, depending on what the image behind it is

![image](https://github.com/user-attachments/assets/edc54d6c-7a66-4832-af59-db7b59dd98c1)

Maybe we could add a double outline, or an inset outline on the button, to ensure focus is always visible.

**Comment by markconroy** [comment]
@msayoung that button is inside an `iframe` which is inside another `iframe`. I'm not sure it's possible for us to do anything to the CSS in that - it comes from YouTube.

**Comment by msayoung** [comment]
:) true. Let's park this for now then.
