### ISSUE TITLE
Remove Menu from Print screen on Guides (overview and pages) and Step by step (overview and pages)Step

### ISSUE THREAD

**Issue by JonathanDHolden** [localgovdrupal/localgov_base#614]
When you go to print these pages, the guide or step by step menu is shown on the page. 

It would be better without the menu, to save paper and make the content more clear. 

It *may* be useful to show which Overview page URL this page references.

**Comment by markconroy** [comment]
Hi @JonathanDHolden 

Can you give this a test please? 
https://github.com/localgovdrupal/localgov_base/pull/615

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by JonathanDHolden** [comment]
Works on Step by Step, but Guide pages I'm still getting the guide menu... @markconroy

**Comment by markconroy** [comment]
Are you sure? I tested Guide pages and it seemed fine. 

Maybe you need to clear your cache?

Here's what I am seeing:

![Screenshot 2024-09-23 at 12 02 06](https://github.com/user-attachments/assets/5622200e-2593-489b-a407-5259c0347ca2)

**Comment by msayoung** [comment]
works for me!

**Comment by JonathanDHolden** [comment]
Tested in Incognito with Hard Reload and Empty cache... Still gets the guide menu... 
https://riverside.265fb764b00f5d8d2b41f1beb5fc7602-13004.sites.k-hosting.co.uk/education/education-health-and-care-plans/education-health-and-care-plan-guide/sections-ehc-plan

**Comment by markconroy** [comment]
@JonathanDHolden judging by your CSS, it looks like you do not have the branch with the changes checked out. 

Here's your CSS from `print.css`

```
.dialog-off-canvas-main-canvas > *:not(.lgd-header, .main),
.lgd-header__inner > *:not(.lgd-region--header),
.lgd-region__inner--header > *:not(.block-system-branding-block),
.sidebar,
.lgd-prev-next,
.newsroom__sidebar {
  display: none;
}
```

It should be:
```
.dialog-off-canvas-main-canvas > *:not(.lgd-header, .main),
.lgd-header__inner > *:not(.lgd-region--header),
.lgd-region__inner--header > *:not(.block-system-branding-block),
.sidebar,
.lgd-prev-next,
.newsroom__sidebar,
.block-localgov-guides-contents,
.block-views-blocklocalgov-step-by-step-navigation-steps-for-overview,
.block-views-blocklocalgov-step-by-step-navigation-steps {
  display: none;
}
```

**Comment by JonathanDHolden** [comment]
Sorry Mark, I'm so used to not having to think about branches etc... (build live in Versoly/ Webflow etc) I forgot about this. I'll check we're on the latest version...
