### ISSUE TITLE
Directory pagination mouse target too narrow

### ISSUE THREAD

**Issue by DavidBAsch** [localgovdrupal/localgov_base#618]
**As a user** browsing directory venues on a desktop

**I need to** have a larger mouse target area on the pagination links

**So that** it's easier to select the required page number

![Image](https://user-images.githubusercontent.com/14923610/234289348-253fe89b-5e53-48e0-b09b-4d60a92dfb75.gif)

**Comment by willguv** [comment]
Cheers @DavidBAsch is this something Chris or Adnan could look at and do a Pull Request for? If not we can look at it

Thanks for coming along today!

**Comment by andybroomfield** [comment]
I think this should be a theme issue, as this will be Drupals standard pagination links which will apply to all listing type pages (events, news, topic views, anything that needs a pager).

**Comment by DavidBAsch** [comment]
@willguv Thanks Will, I have a Trello card already so I'll update accordingly.

**Comment by andybroomfield** [comment]
@markconroy Shall we move this to localgov_base? Although it's icebox'd at the moment.

**Comment by markconroy** [comment]
Yep, let's move this to LocalGov Base. Thanks.
