### ISSUE TITLE
Theme refactor: Alert Banner

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#62]
# Sample: http://localgov.dev.mark.ie/

[] Put the templates in place in the theme
[] Move styling into localgov_base theme
[] confirm feature parity

**Comment by andybroomfield** [comment]
Are we fully moving the templates and CSS out of alert banner into the theme?
We need templates in the alert banner module as its a custom entity.
I thought we also where planning on keeping basic CSS for the alert banner so it works out the box?

**Comment by markconroy** [comment]
Hi @andybroomfield 

I'm just moving things to the theme for now, so we can see how it works. We can then start backporting them to modules. The alert banner is a good example of where things should remain in the module.

**Comment by markconroy** [comment]
Hi @andybroomfield 

I don't see any changes needed in the Alert Banner for the new theme, except to change this class name (which won't affect anything) - https://github.com/localgovdrupal/localgov_alert_banner/pull/157

I'll close this issue and leave that PR to you.
