### ISSUE TITLE
Upgrade helper

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_base#624]
Moving from 1.6 to 1.7 a dependency is added on a (sub-)module which is not enabled by the theme (one of the reasons to have a module is to be able to add update hooks!)

Just adding the dependency to the profile, or even core, won't enable the module on existing sites. It will mean that the theme can be enabled on _new_ sites however.

The sites however do _not_ break. There is a notification on the Themes page that the theme requires a module to be enabled. We could however help this by adding an update hook elsewhere that checks to see if this theme is enabled, and if so enables the module. If it doesn't enable the module, the end of the world is not met, and there is site admin notification (although this could also be better if modules can have a hook_dependencies).

**Comment by ekes** [comment]
As
 (a) this helper is _not_ _required_ but only a bonus;
 (b) we are enabling the theme in the profiles at the moment;
 (c) we are enabling for new sites the module, and need to hence have a dependency on the version of this theme, in the profiles at the moment;
it seems correct that the update hook should go in this case into the profile.

**Comment by ekes** [comment]
I don't seem to get hook_requirements to work in a theme, so the notification on the theme page for those who don't have a profile, or somehow manage not to get the update otherwise, will have to just have the notification there.

**Comment by millnut** [comment]
Yep hook_requirements don't work in the theme https://www.drupal.org/project/drupal/issues/2652542. I think we should add an update hook in the profile to handle exisitng websites for this case

**Comment by ekes** [comment]
>  I think we should add an update hook in the profile to handle exisitng websites for this case

Like

https://github.com/localgovdrupal/localgov_base/pull/622#issuecomment-2374875960

;-)

It's just you don't need the profile installed. So it's nice to give notification (and not break) for those that don't get the update. The notification is actually there on the theme page, so it's not bad.

**Comment by andybroomfield** [comment]
Is there a way to wrap code that needs the helper to check the module exists, and if not set a message (to admins only) that it needs to be enabled when the functionality is called?

**Comment by finnlewis** [comment]
Discussing on Merge Tuesday:

 - @markconroy is keen to do a release to get other recent updates out in the wild. 
 - No one particularly needs the sticky header, that we know of.
 - Fo now, maybe we remove the module and dependency and tag a release?

Then create a branch for the localgov_base_helper and continue to explore?

**Comment by markconroy** [comment]
Here's the PR to remove the helper module - https://github.com/localgovdrupal/localgov_base/pull/632

**Comment by ekes** [comment]
Upgrade helper removed, so I think we can close this one.
