### ISSUE TITLE
Theme refactor: Service Status Nodes

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#63]
Sample in-service-page block: http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship
Sample statuses list page: http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship/status
Sample status node: http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship/status/status-limited-service-impact-issue

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme
[x] confirm feature parity

![Screenshot 2021-06-29 at 21 23 31](https://user-images.githubusercontent.com/2183332/123862646-821c3680-d920-11eb-92e2-2103bfd627d6.jpg)

**Comment by markconroy** [comment]
PR #72

**Comment by danchamp** [comment]
Thanks @markconroy, looking good. A small number of comments:

- The 'Read more' links in `service-status-page.html.twig` and `service-status-block.html.twig` lack context for screen readers when there is more than one status live. The module's `node--localgov-services-status--message.html.twig` template uses an `aria-label` to fix this:

https://github.com/localgovdrupal/localgov_services/blob/fce560fa733620fe56fa97e3c3830d8fa9f9a222/modules/localgov_services_status/templates/node--localgov-services-status--message.html.twig#L88

Happy to repeat this approach here. (There's also a [long-standing issue](https://github.com/localgovdrupal/localgov_services/issues/60) for this in the module that I'll fix once we settle on an approach here.)

- The 'See all' link at the foot of the list block doesn't have the same margin/padding as in your screen grab above:

<img width="448" alt="Screenshot 2021-06-30 at 10 34 37" src="https://user-images.githubusercontent.com/261421/123938267-e07ffe00-d98e-11eb-9143-bd5472c5886b.png">

- The `<time>` element (in block and page templates) should either have a `datetime` attribute with a machine-readable date (e.g. Y-m-d) or the text content should be in a machine-readable format. I think we want the former, and leave the visible date as-is?
- A minor issue with heading levels - the **Service updates** `<h2>` in the block template is omitted from `service-status-page.html.twig` resulting in a skip from `<h1>` to `<h3>`. We could either add an `<h2>` (possibly visually-hidden) at the top of the list in the page template, or promote the update titles to `<h2>` in this template.

**Comment by danchamp** [comment]
@markconroy One more comment - the 'See all' link text would be better extended to 'See all service updates' for screen reader users to provide context, either using an `aria-label` (preferable) or additional hidden text.

**Comment by markconroy** [comment]
Thanks Dan. 

I have those all fixed now.

For the jump from h1 -> h3, I just changed the heading level in the template for that template (we have 2 templates, one for each block, so it was easy).

**Comment by danchamp** [comment]
Excellent, thanks @markconroy this is good for me.
