### ISSUE TITLE
Theme Refactor: Banner Primary

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#64]
# Sample: http://localgov.dev.mark.ie/bereavement-services

[] Put the templates in place in the theme
[] Move styling into localgov_base theme
[] confirm feature parity

**Comment by markconroy** [comment]
PR #74

**Comment by msayoung** [comment]
Looks good 

A more general question about these. Does it make sense that the banner appears before the Alert banners? 

Also, I had assumed that the banners would be providing the H1 on the page, but I think I am/was mistaken. More on that over here: https://github.com/localgovdrupal/localgov_subsites/issues/26

**Comment by danchamp** [comment]
@markconroy Looks good for me too, thanks.

Agree with @msayoung that alert banners should precede these.

**Comment by markconroy** [comment]
The order of banner vs alert is a block config item, not something got to do with the team. We'll have to create an issue in localgov_alerts or localgov_subsites to set the weight for those.

**Comment by danchamp** [comment]
> The order of banner vs alert is a block config item, not something got to do with the team. We'll have to create an issue in localgov_alerts or localgov_subsites to set the weight for those.

Issue raised: https://github.com/localgovdrupal/localgov_alert_banner/issues/153
