### ISSUE TITLE
Add composer.json file to theme

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#65]

**Comment by andybroomfield** [comment]
Bump and also add this to Packagist.
(Or get this and the other Localgov Drupal modules listed on Drupal.org)

**Comment by markconroy** [comment]
Hi @danchamp 

What's needed on this issue to close it?

**Comment by danchamp** [comment]
@markconroy I think it can be closed now, it was a short-term issue when composer.json was removed in this update: https://github.com/localgovdrupal/localgov_base/pull/74/files
