### ISSUE TITLE
Automate CSS coding standards via stylelint

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#69]
All the CSS we currently have is ordered by me, hoping it's in the right order for Drupal standards. Let's set up a package.json file and npm script to auto-format our CSS, so that _everyone_ follows the coding standards without even realising it.

**Comment by markconroy** [comment]
PR #86

**Comment by msayoung** [comment]
Nice, can we add a line about how to run it in the Readme ?

**Comment by markconroy** [comment]
Yes. I'll close this add add that line.
