### ISSUE TITLE
Accessibility audit of base theme.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#79]
Dan is keen to perform an initial accessibility audit of the full install with the new localgov_base theme.

This will be for internal purposes (producing issues for further work) rather than an external report.

**Comment by msayoung** [comment]
Log here: https://docs.google.com/spreadsheets/d/1t8rRIQe_1kogxPBZDKcsbf8YxtEfC9iGJvidkagNSXY/edit#gid=1779042480

**Comment by markconroy** [comment]
Hi @msayoung  and @danchamp 

Just want to check in here about the items being logged in the spreadsheet. Am I to fix all those or are we dividing them up, or are we/you/me fixing as we come across them?

**Comment by danchamp** [comment]
@markconroy The plan was to begin raising the issues on GitHub this week, in priority order (highest value first), and fix those that are straightforward as we go. Other issues will require dev input in the respective modules.

It's a group effort, if you've got time/capacity please make a start and update the log sheet as you go but there's no expectation that you're to fix them all.

**Comment by markconroy** [comment]
Thanks a lot, Dan.

**Comment by stephen-cox** [comment]
Done - sprint 6
