### ISSUE TITLE
Theme refactor frontend:  localgov_services

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#8]
- [ ] Put the templates in place in the theme
- [ ] Move styling into localgov_base theme.
- [ ] confirm feature parity 

Estimate: 13

Note: @markconroy and @msayoung thinks this might be bigger.

@todo: Split out the tasks if needed. 

I've split this into 3 issues - one for each content type.

**Comment by markconroy** [comment]
Sub tasks:
1. Service landing page - https://github.com/localgovdrupal/localgov_base/issues/14
2. Service sub-landing page - https://github.com/localgovdrupal/localgov_base/issues/15
3. Service node page - https://github.com/localgovdrupal/localgov_base/issues/15

**Comment by markconroy** [comment]
Marking this as "done" since it's broken into 3 separate cards.
