### ISSUE TITLE
Theme Re-factor: News/Newsroom/News Lists

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#80]
# Sample newsroom: http://localgov.dev.mark.ie/news
# Sample news article: http://localgov.dev.mark.ie/news/2021/test-news-post-number-2-really-important-one

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme
- [x] confirm feature parity

**Comment by markconroy** [comment]
PR #81

**Comment by danchamp** [comment]
@markconroy Looking good, thanks. A couple of questions:

1. Can we include the search form on the search page, as we do with events and directories? (This may be a module issue.)
2. Can we make it easier to switch the sidebar to the right side? At present I need to over-ride the whole template. Alternatively, we could default to having the sidebar on the right side, matching the pattern at [BHCC](http://design.brighton-hove.gov.uk/markup/newsroom-home.php), [London Councils](https://beta.londoncouncils.gov.uk/), and [Croydon](https://news.croydon.gov.uk/)?

**Comment by markconroy** [comment]
Hi @danchamp 

The sidebar issue really ought to be config, not in a template. I think those items in the sidebar should be blocks placed in the sidebar (or any region you want them) and not hardcoded as extra fields on the content type. But that's a module issue, not a theme issue. @ekes any thoughts on this?

Including the search form on the search page is also a module issue. I was only dealing with what was presented out of the box. If that gets added to the page, I can get it themed very easily.

@danchamp  are you okay to close this issue and create new issues in the localgov_news repo for those two items?

**Comment by danchamp** [comment]
@markconroy Yes, very happy to do that. I'll close and move to review completed, and raise an issue in localgov_news.
