### ISSUE TITLE
External link mask-image CSS property needs -webkit- prefix

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#87]
`mask-image` needs a -webkit- vendor prefix for Chromium/Webkit browsers:

https://github.com/localgovdrupal/localgov_base/blob/3387b0ff546de5b51b0ee1fd572d1ab8f5eca743/css/components/wysiwyg-styles.css#L65

**Comment by markconroy** [comment]
Thanks @danchamp 

That's added now.
