### ISSUE TITLE
Service landing page email link href renders with line breaks

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#95]
Use `node.localgov_email_address.value` instead of `content.localgov_email_address|render|striptags|trim`:

https://github.com/localgovdrupal/localgov_base/blob/65bcca8af8a4bb1529217ea12223b7e089055829/templates/content/node--localgov-services-landing--full.html.twig#L97

**Comment by markconroy** [comment]
PR #106
